import { useMemo, useState } from "react";
import { Activity, CheckCircle2, CircleHelp, Gauge, Move3D, Plane, RotateCcw, Scale, ShieldAlert, XCircle } from "lucide-react";

const questions = [
  { question: "Which drone type is normally best suited to hovering in one place?", options: ["Multirotor", "Conventional fixed wing", "Unpowered glider", "Parachute"], answer: 0 },
  { question: "What does a quadcopter's wheelbase usually describe?", options: ["The distance between opposing motor axes", "The battery voltage", "The propeller pitch", "The GPS antenna height"], answer: 0 },
  { question: "Why do neighbouring rotors normally spin in opposite directions?", options: ["To balance reaction torque", "To double battery voltage", "To improve camera colour", "To change the frame material"], answer: 0 },
  { question: "What happens when total upward rotor thrust is approximately equal to aircraft weight?", options: ["The aircraft can maintain altitude", "The aircraft must yaw rapidly", "The battery becomes fully charged", "The frame becomes weightless"], answer: 0 },
  { question: "How does a quadcopter normally initiate forward pitch?", options: ["It creates a controlled thrust difference that tilts the thrust vector forward", "It reverses every motor", "It turns off the rear receiver", "It removes the front propellers"], answer: 0 },
  { question: "Why should the centre of gravity be close to the intended geometric/thrust centre?", options: ["To reduce constant corrective effort and improve predictable control", "To increase radio frequency", "To change GPS coordinates", "To charge cells equally"], answer: 0 },
  { question: "What does a thrust-to-weight ratio greater than 1 indicate in principle?", options: ["Available maximum thrust exceeds weight", "The drone cannot climb", "The aircraft has no drag", "The battery is damaged"], answer: 0 },
  { question: "What is a likely effect of a flexible or cracked frame arm?", options: ["Vibration and changing motor alignment can degrade control", "GPS becomes perfectly accurate", "Flight time always doubles", "The propeller balances itself"], answer: 0 },
  { question: "Why is propeller clearance checked during frame design?", options: ["Overlapping or contacting propeller discs can cause catastrophic damage", "It changes the legal airspace", "It encrypts telemetry", "It calibrates the compass"], answer: 0 },
  { question: "What is the correct safety condition for measuring static thrust on a test stand?", options: ["A secured rated stand, guarded area, remote operation and suitable protection", "Holding the motor by hand", "Testing over spectators", "Using a damaged propeller"], answer: 0 },
];

export default function DroneChapterTwoLesson() {
  return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
    <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 2</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Drone Types, Frames and Multirotor Aerodynamics</h2><p className="mt-4 leading-8 text-slate-600">Aircraft architecture determines how a drone launches, carries a payload, moves through air and responds to disturbances. This chapter compares common configurations and develops the frame, force, balance and control concepts needed before selecting propulsion components.</p></header>

    <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Compare multirotor, fixed-wing and hybrid VTOL aircraft.", "Identify quad, hexa and octocopter trade-offs.", "Explain frame geometry, wheelbase and propeller clearance.", "Relate thrust, weight and drag to hover and movement.", "Explain roll, pitch and yaw through differential rotor thrust.", "Estimate thrust-to-weight ratio and assess centre-of-gravity placement."].map(item=><li key={item} className="rounded-xl border border-slate-200 p-4"><b className="mr-2 text-emerald-600">✓</b>{item}</li>)}</ul></section>

    <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><Plane className="text-blue-700"/><h3 className="text-2xl font-bold">Choosing an aircraft architecture</h3></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Card title="Multirotor" text="Excellent hover and low-speed control. Mechanically compact, but continuous rotor power limits endurance."/><Card title="Fixed wing" text="Efficient in forward flight and suitable for wide-area coverage. Requires airspeed and more launch, landing and turning space."/><Card title="Hybrid VTOL" text="Vertical takeoff plus efficient wing-borne cruise. Added motors, mass, control modes and transitions increase complexity."/></div></section>

    <section><h3 className="text-2xl font-bold">Multirotor layouts</h3><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Layout</th><th className="p-3">Strength</th><th className="p-3">Trade-off</th><th className="p-3">Typical use</th></tr></thead><tbody className="divide-y"><tr><td className="p-3 font-semibold">Tricopter</td><td className="p-3">Low motor count</td><td className="p-3">Yaw mechanism and asymmetric geometry add complexity</td><td className="p-3">Experimental/light builds</td></tr><tr><td className="p-3 font-semibold">Quadcopter</td><td className="p-3">Simple, efficient and widely supported</td><td className="p-3">A single propulsion failure is normally critical</td><td className="p-3">Training, imaging, inspection</td></tr><tr><td className="p-3 font-semibold">Hexacopter</td><td className="p-3">More lift and possible fault tolerance when designed accordingly</td><td className="p-3">Higher mass, cost and energy use</td><td className="p-3">Heavier payloads</td></tr><tr><td className="p-3 font-semibold">Octocopter</td><td className="p-3">High lift and propulsion redundancy potential</td><td className="p-3">Large, expensive and power hungry</td><td className="p-3">Specialised professional payloads</td></tr></tbody></table></div><p className="mt-4 text-sm leading-6 text-slate-500">Extra motors do not automatically guarantee safe continued flight; the frame, power system, controller, firmware and operating plan must all support the intended failure response.</p></section>

    <section className="rounded-2xl border border-sky-200 bg-sky-50 p-6"><div className="flex items-center gap-3"><Activity className="text-sky-700"/><h3 className="text-2xl font-bold">Rotor thrust and reaction torque</h3></div><p className="mt-4 leading-8 text-slate-700">Each rotor produces an aerodynamic force by accelerating air. The motor also applies torque to the propeller, and the airframe experiences an opposing reaction. A quadcopter normally uses two clockwise and two counter-clockwise rotor systems so their reaction torques approximately cancel in steady hover. Changing the balance of these torques produces yaw.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Rotor direction" text="The flight-controller motor map, motor rotation and correct propeller type must agree. A mismatch can cause an immediate flip."/><Card title="Propeller disc" text="The swept circular area must have safe clearance from neighbouring propellers, the frame, wiring and payload."/></div></section>

    <section><div className="flex items-center gap-3"><Move3D className="text-indigo-700"/><h3 className="text-2xl font-bold">Roll, pitch and yaw</h3></div><p className="mt-4 leading-8 text-slate-600">A multirotor tilts by producing controlled differences in rotor thrust. The resulting total thrust vector gains a horizontal component, accelerating the aircraft sideways or forward. Roll is rotation about the longitudinal axis, pitch about the lateral axis, and yaw about the vertical axis. The exact motor mixing depends on frame layout and firmware convention.</p><div className="mt-5 grid gap-4 md:grid-cols-3"><Card title="Roll" text="A left-right thrust difference tilts the aircraft sideways."/><Card title="Pitch" text="A front-rear thrust difference tilts the aircraft forward or backward."/><Card title="Yaw" text="A change in the balance of clockwise and counter-clockwise reaction torques rotates heading."/></div></section>

    <section className="rounded-2xl bg-emerald-50 p-6"><div className="flex items-center gap-3"><Scale className="text-emerald-700"/><h3 className="text-2xl font-bold">Thrust-to-weight ratio</h3></div><p className="mt-4 leading-8 text-slate-700"><b>Thrust-to-weight ratio = maximum total available thrust ÷ aircraft weight.</b> A value of 1 means maximum thrust only equals weight in the assumed conditions; it provides no useful control margin. Designers need margin for manoeuvre, wind, battery-voltage reduction, manufacturing variation and safe operation. Use verified manufacturer/test data and design for the mission instead of treating one universal ratio as correct.</p><div className="mt-5 rounded-xl bg-white p-5"><h4 className="font-bold">Illustrative calculation</h4><p className="mt-2 text-slate-600">Four motor/propeller units each measured at 800 g-force maximum static thrust provide 3,200 gf total. If the all-up mass is 1,600 g, the idealised static ratio is 3,200 ÷ 1,600 = 2.0. Real performance will differ with air density, voltage, component heating, airflow interaction and measurement accuracy.</p></div></section>

    <section><div className="flex items-center gap-3"><Gauge className="text-blue-700"/><h3 className="text-2xl font-bold">Frame geometry and centre of gravity</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Rigid and aligned" text="Arms must resist bending and twisting. Motor mounting faces should remain aligned so thrust points in the intended directions."/><Card title="Light but durable" text="Unnecessary mass consumes thrust and energy, while an under-designed frame can flex, crack or fail."/><Card title="Balanced layout" text="Place the battery and payload so the centre of gravity is close to the intended thrust/geometric centre unless the design specifies otherwise."/><Card title="Low vibration" text="Balanced propellers, sound bearings, secure fasteners and suitable controller mounting protect sensor measurements."/></div></section>

    <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-red-700"/><h3 className="text-2xl font-bold">Propeller and test safety</h3></div><ul className="mt-4 space-y-2 text-slate-700"><li>• Treat every fitted propeller as a sharp, high-energy rotating tool.</li><li>• Remove propellers during firmware setup, receiver checks, motor assignment and direction testing.</li><li>• Never use cracked, chipped, deformed or incorrectly specified propellers.</li><li>• Do not stand in the propeller plane or reach over an armed aircraft.</li><li>• Static-thrust testing requires a rated, secured stand, remote control, exclusion area and appropriate guarding/protection.</li><li>• Verify fastener method and tightening requirements for the exact motor and propeller system.</li></ul></section>

    <section className="rounded-2xl bg-slate-900 p-6 text-white"><h3 className="text-2xl font-bold">Hands-on design activity</h3><p className="mt-3 leading-7 text-slate-200">Create a paper design for a training quadcopter. Specify X or plus geometry, wheelbase, proposed propeller diameter, minimum blade-tip clearance, estimated frame mass, battery and payload positions, and estimated all-up mass. Use assumed per-motor thrust to calculate an illustrative thrust-to-weight ratio. Mark the intended centre of gravity and explain how you would move the battery to correct imbalance. This is a design exercise—do not energise a propulsion system.</p></section>

    <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-950">Chapter completion checklist</h3><p className="mt-3 leading-7 text-blue-900">Compare the three aircraft architectures, explain multirotor torque balance and control axes, complete the frame layout and thrust-to-weight activity, identify propeller safety controls, and score at least 80% below.</p></section>
  </article><ChapterQuiz/></>;
}

function ChapterQuiz(){const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;const reset=()=>{setAnswers({});setSubmitted(false)};return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b border-slate-200 pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 2 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border border-slate-200 p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=answers[i]===j;const correct=submitted&&j===q.answer;const incorrect=submitted&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":incorrect?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"border-slate-200 hover:bg-slate-50"}`}><input type="radio" name={`drone-ch2-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(a=>({...a,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!submitted?<button type="button" disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button type="button" onClick={reset} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}

function Card({title,text}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><h4 className="font-bold text-slate-900">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
