import { useMemo, useState } from "react";
import { CheckCircle2, CircleHelp, Fence, MapPinned, RotateCcw, Route, ShieldAlert, Siren, XCircle } from "lucide-react";

const questions=[
 {question:"What is the purpose of an autonomous mission plan?",options:["Define an authorised sequence of navigation actions and contingencies","Replace all airspace checks","Increase motor KV","Guarantee obstacle avoidance"],answer:0},
 {question:"Why must altitude references be confirmed?",options:["They change battery chemistry","Different mission, home, terrain and regulatory references can produce different heights","They determine radio colour","They balance propellers"],answer:1},
 {question:"What is a geofence?",options:["A physical motor guard","A software-defined operational boundary or limit","A battery connector","A camera filter"],answer:1},
 {question:"What should happen before uploading a mission?",options:["Install larger propellers","Validate every waypoint, command, altitude, speed and end action","Disable fail-safes","Arm indoors"],answer:1},
 {question:"Why is a geofence not a substitute for legal planning?",options:["It cannot establish permission, detect every obstacle or eliminate navigation error","It always disables GPS","It is only decorative","It powers the receiver"],answer:0},
 {question:"What is a safe way to introduce autonomous flight?",options:["Start with the longest route","Test above people","Use simulation and then a short supervised mission in a clear authorised area","Disable manual override"],answer:2},
 {question:"What should a mission contingency matrix include?",options:["Only frame colour","Trigger, detection, configured action, pilot action and recovery criteria","Only battery size","Only waypoint count"],answer:1},
 {question:"What is important when configuring Return-to-Launch?",options:["A valid home position, suitable return altitude/path and landing behaviour","Only camera resolution","Maximum radio volume","Propeller packaging"],answer:0},
 {question:"What should the operator do when the mission path or map does not match the real site?",options:["Launch and correct later","Increase speed","Abort planning and resolve the discrepancy before flight","Ignore it if GPS has a fix"],answer:2},
 {question:"What is the safest response to an unexplained autonomous mode change or fence breach?",options:["Continue the mission","Disable warnings","Fly farther away","Use the prepared recovery action, land safely and investigate before another mission"],answer:3},
];

export default function DroneChapterNineLesson(){return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
 <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 9</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Autonomous Missions, Geofencing and Fail-Safes</h2><p className="mt-4 leading-8 text-slate-600">Autonomy executes a plan; it does not remove operator responsibility. Safe missions require verified navigation, current site and airspace information, explicit boundaries, predictable contingencies, manual recovery skills and staged testing that proves each assumption before operational use.</p></header>
 <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Build and validate a waypoint mission from objective to landing.","Reconcile coordinate, altitude, terrain and speed references.","Explain inclusion, exclusion, altitude and distance geofences.","Design layered responses for radio, battery, GNSS and telemetry faults.","Use simulation and staged testing before complex autonomous flight.","Prepare a mission briefing, contingency matrix and post-flight review."].map(x=><li key={x} className="rounded-xl border border-slate-200 p-4"><b className="mr-2 text-emerald-600">✓</b>{x}</li>)}</ul></section>
 <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><Route className="text-blue-700"/><h3 className="text-2xl font-bold">From mission objective to executable plan</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Objective and authority" text="Define the task, operating area, approvals, crew responsibilities, privacy constraints and success criteria."/><Card title="Route and commands" text="Check every waypoint, command, speed, yaw action, hold, payload event and mission end behaviour."/><Card title="Energy and time" text="Estimate climb, wind, route and reserve demands; set conservative abort points before battery fail-safe."/><Card title="Recovery" text="Specify safe hold, return, land or pilot-takeover actions for each credible fault and site constraint."/></div></section>
 <section><div className="flex items-center gap-3"><MapPinned className="text-indigo-700"/><h3 className="text-2xl font-bold">Coordinates, altitude and terrain</h3></div><p className="mt-4 leading-8 text-slate-600">Confirm map datum, waypoint coordinates and the meaning of altitude in the selected flight stack: relative to home, above terrain, absolute or another reference. Map imagery and terrain models may be old, incomplete or inaccurate. Validate the actual launch point, obstacles, surface, slope, return corridor and landing zone with current authoritative information and on-site observation.</p><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Mission item</th><th className="p-3">Validation</th><th className="p-3">Failure risk</th></tr></thead><tbody className="divide-y"><tr><td className="p-3 font-semibold">Waypoint</td><td className="p-3">Coordinate, sequence, acceptance radius</td><td className="p-3">Wrong location or unintended shortcut</td></tr><tr><td className="p-3 font-semibold">Altitude</td><td className="p-3">Reference, terrain and obstacle margin</td><td className="p-3">Ground/obstacle conflict or rule breach</td></tr><tr><td className="p-3 font-semibold">Speed</td><td className="p-3">Aircraft, wind, turn and stopping limits</td><td className="p-3">Overshoot or inadequate energy reserve</td></tr><tr><td className="p-3 font-semibold">Final action</td><td className="p-3">Hold, return or landing site/approach</td><td className="p-3">Unexpected continued flight or unsafe descent</td></tr></tbody></table></div></section>
 <section className="rounded-2xl bg-indigo-50 p-6"><div className="flex items-center gap-3"><Fence className="text-indigo-700"/><h3 className="text-2xl font-bold">Geofence layers</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Maximum distance" text="Restricts horizontal travel from a defined reference such as home, subject to navigation accuracy."/><Card title="Altitude limit" text="Constrains vertical operation using the configured altitude reference; it must agree with legal and site limits."/><Card title="Inclusion area" text="Defines the region intended for operation and should include safe manoeuvre/recovery margin."/><Card title="Exclusion area" text="Marks places the plan must avoid, but cannot substitute for obstacle sensing or airspace permission."/></div><p className="mt-5 leading-7 text-slate-700">Test fence enablement, boundary geometry and breach action using simulation or the flight stack&apos;s safe documented method. Navigation error, delayed response and vehicle momentum require margins inside the legal and physical boundary.</p></section>
 <section><h3 className="text-2xl font-bold">Layered fail-safe planning</h3><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Trigger</th><th className="p-3">Questions to answer</th></tr></thead><tbody className="divide-y"><tr><td className="p-3 font-semibold">Radio loss</td><td className="p-3">How detected? Is navigation valid? Hold, return or land? Can the link recover safely?</td></tr><tr><td className="p-3 font-semibold">Low/critical battery</td><td className="p-3">Are thresholds under-load and conservative? Is the landing/return energy reserve sufficient?</td></tr><tr><td className="p-3 font-semibold">GNSS/estimator fault</td><td className="p-3">Which modes remain controllable? What pilot mode and landing area are prepared?</td></tr><tr><td className="p-3 font-semibold">Fence breach</td><td className="p-3">What action occurs, which limits have priority, and could that action create a new hazard?</td></tr><tr><td className="p-3 font-semibold">Telemetry loss</td><td className="p-3">Does RC remain? What monitoring/command capability is lost and when must the mission stop?</td></tr></tbody></table></div></section>
 <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-center gap-3"><Siren className="text-amber-700"/><h3 className="text-2xl font-bold">Staged mission validation</h3></div><ol className="mt-5 space-y-3">{["Review current rules, airspace, weather, site hazards, privacy and permissions.","Validate the mission and fence independently using a checklist and second-person review where possible.","Run software-in-the-loop or approved simulation to observe route, final action and injected failures.","With propellers removed, verify upload, mission item count, modes, warnings and pilot override.","Fly a short supervised low-complexity mission in a clear authorised area with generous margins.","Introduce only one new feature or failure test at a time and preserve an immediate recovery mode.","Land, disarm and compare actual track, events, energy and estimator status with the plan.","Approve expansion only when deviations are understood, corrected and documented."].map((x,i)=><li key={x} className="flex gap-4 rounded-xl bg-white p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-amber-600 text-sm font-bold text-white">{i+1}</span>{x}</li>)}</ol></section>
 <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-red-700"/><h3 className="text-2xl font-bold">Autonomy stop conditions</h3></div><p className="mt-4 leading-8 text-slate-700">Do not start or continue a mission when permissions, route, altitude reference, home, fence, weather, positioning, battery reserve, communications, pilot override or landing area are uncertain. On an unexpected mode change, route deviation, fence event, conflicting fail-safe or loss of situational awareness, use the briefed recovery action, land safely and investigate logs before another flight.</p></section>
 <section className="rounded-2xl bg-slate-900 p-6 text-white"><h3 className="text-2xl font-bold">Hands-on activity: mission package and contingency matrix</h3><p className="mt-3 leading-7 text-slate-200">Create a simulated training mission with objective, map, waypoint table, altitude reference, speeds, energy estimate, fence diagram, launch/landing zones and legal/site constraints. Add a matrix for radio loss, GNSS fault, low battery, telemetry loss, fence breach and weather change, listing detection, automatic action, pilot action and recovery criteria. Validate it in simulation and record every discrepancy—do not conduct a real autonomous flight unless authorised, competent and supervised.</p></section>
 <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-950">Chapter completion checklist</h3><p className="mt-3 leading-7 text-blue-900">Validate every mission item and altitude reference, explain fence limitations, complete the contingency matrix, demonstrate staged simulation evidence, state pilot-recovery and stop criteria, and score at least 80% below.</p></section>
</article><ChapterQuiz/></>}

function ChapterQuiz(){const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;const reset=()=>{setAnswers({});setSubmitted(false)};return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b border-slate-200 pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 9 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border border-slate-200 p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=answers[i]===j;const correct=submitted&&j===q.answer;const incorrect=submitted&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":incorrect?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"border-slate-200 hover:bg-slate-50"}`}><input type="radio" name={`drone-ch9-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(a=>({...a,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!submitted?<button type="button" disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button type="button" onClick={reset} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}
function Card({title,text}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><h4 className="font-bold text-slate-900">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
