import { useMemo, useState } from "react";
import { Activity, BrainCircuit, CheckCircle2, CircleHelp, Compass, Cpu, Gauge, RotateCcw, ShieldAlert, SlidersHorizontal, Vibrate, XCircle } from "lucide-react";

const questions = [
  { question: "What is the primary role of a flight controller?", options: ["Store camera photographs", "Estimate aircraft state and command actuators for control", "Supply motor phase current directly", "Replace the radio receiver"], answer: 1 },
  { question: "What does a gyroscope measure?", options: ["Angular rotation rate", "Battery capacity", "GPS coordinates", "Airframe mass"], answer: 0 },
  { question: "What does an accelerometer sense?", options: ["Only geographic north", "Specific force, including the apparent effect of gravity", "Radio frequency", "Propeller diameter"], answer: 1 },
  { question: "Why are multiple sensors combined in state estimation?", options: ["Every sensor has different strengths, noise and failure modes", "To increase motor KV", "To change the frame size", "To charge the battery"], answer: 0 },
  { question: "What can severe vibration do to an IMU?", options: ["Improve every estimate", "Corrupt measurements and degrade stabilisation", "Increase GPS satellites", "Balance the propellers"], answer: 1 },
  { question: "Why must flight-controller orientation be configured correctly?", options: ["The controller must map sensor axes to the aircraft axes", "It changes LiPo chemistry", "It sets the legal airspace", "It determines camera storage"], answer: 0 },
  { question: "What is the purpose of accelerometer calibration?", options: ["Measure propeller pitch", "Estimate and correct sensor offsets/scaling across known orientations", "Bind the receiver", "Program the ESC"], answer: 1 },
  { question: "What does the inner rate-control loop normally regulate?", options: ["Angular rotation rates", "Course enrollment", "Battery charging", "GPS map colour"], answer: 0 },
  { question: "What is integrator windup?", options: ["A propeller gust", "Excess accumulated integral correction during sustained error or actuator saturation", "A compass calibration", "A battery warning"], answer: 1 },
  { question: "What is the safest response to unresolved estimator or sensor-health warnings?", options: ["Arm and test at full throttle", "Disable all warnings", "Do not fly until the cause is understood and corrected", "Increase propeller size"], answer: 2 },
];

export default function DroneChapterFourLesson(){return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
  <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 4</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Flight Controllers, IMU Sensors and Stabilisation</h2><p className="mt-4 leading-8 text-slate-600">A multirotor is naturally demanding to control because motor thrust, disturbances and aircraft motion change continuously. The flight controller closes this loop: it reads sensors, estimates orientation and motion, compares them with pilot or navigation targets, and updates motor commands many times per second.</p></header>

  <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Identify the main hardware and software blocks in a flight controller.", "Explain the roles and limitations of gyro, accelerometer, compass and barometer sensors.", "Describe sensor fusion and attitude/state estimation conceptually.", "Distinguish angular-rate, attitude, altitude and position control loops.", "Plan safe orientation, calibration and pre-arm validation steps.", "Recognise vibration, magnetic interference, estimator and saturation problems."].map(item=><li key={item} className="rounded-xl border border-slate-200 p-4"><b className="mr-2 text-emerald-600">✓</b>{item}</li>)}</ul></section>

  <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><Cpu className="text-blue-700"/><h3 className="text-2xl font-bold">Flight-controller architecture</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card icon={Activity} title="Sensor acquisition" text="Reads IMUs and supporting sensors with timestamps and health checks."/><Card icon={BrainCircuit} title="State estimation" text="Combines measurements and a motion model to estimate attitude, velocity, position and sensor bias."/><Card icon={SlidersHorizontal} title="Control laws" text="Compare demanded and estimated motion, then calculate roll, pitch, yaw and thrust corrections."/><Card icon={Cpu} title="Output mixing" text="Converts control demands into motor commands according to the configured airframe geometry."/></div><p className="mt-5 leading-7 text-slate-700">The controller also manages arming checks, logging, communications, flight modes, navigation, limits and fail-safe actions. Hardware alone does not define behaviour: board orientation, firmware, parameters, wiring and vehicle type must agree.</p></section>

  <section><h3 className="text-2xl font-bold">The core sensors</h3><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Sensor</th><th className="p-3">Measures</th><th className="p-3">Strength</th><th className="p-3">Limitation</th></tr></thead><tbody className="divide-y"><tr><td className="p-3 font-semibold">Gyroscope</td><td className="p-3">Angular rate</td><td className="p-3">Fast rotational response</td><td className="p-3">Bias accumulates into orientation drift</td></tr><tr><td className="p-3 font-semibold">Accelerometer</td><td className="p-3">Specific force</td><td className="p-3">Provides gravity-related reference in suitable conditions</td><td className="p-3">Motion and vibration disturb interpretation</td></tr><tr><td className="p-3 font-semibold">Magnetometer</td><td className="p-3">Magnetic field</td><td className="p-3">Helps constrain heading</td><td className="p-3">Affected by current, steel and magnets</td></tr><tr><td className="p-3 font-semibold">Barometer</td><td className="p-3">Air pressure</td><td className="p-3">Supports relative altitude estimation</td><td className="p-3">Prop wash, weather and enclosure pressure affect readings</td></tr></tbody></table></div></section>

  <section className="rounded-2xl bg-indigo-50 p-6"><div className="flex items-center gap-3"><BrainCircuit className="text-indigo-700"/><h3 className="text-2xl font-bold">Sensor fusion and state estimation</h3></div><p className="mt-4 leading-8 text-slate-700">No single sensor provides a complete, drift-free description of the aircraft. An estimator such as an extended Kalman filter uses a mathematical motion model plus gyro, accelerometer and available supporting measurements to estimate orientation, velocity, position and sensor offsets while accounting for uncertainty. Innovation or consistency checks help identify measurements that disagree with the expected state.</p><div className="mt-5 grid gap-4 md:grid-cols-3"><Card icon={Gauge} title="Prediction" text="Advance the state estimate using the previous state, time and motion model."/><Card icon={Compass} title="Measurement update" text="Compare predicted quantities with available sensor observations."/><Card icon={CheckCircle2} title="Health and uncertainty" text="Weight measurements, track confidence and expose faults or excessive disagreement."/></div></section>

  <section><div className="flex items-center gap-3"><SlidersHorizontal className="text-emerald-700"/><h3 className="text-2xl font-bold">Nested stabilisation loops</h3></div><p className="mt-4 leading-8 text-slate-600">Multirotor control is commonly layered. An outer loop converts a higher-level target into a lower-level target; a faster inner loop regulates angular rates and sends corrections to the mixer. Exact implementations differ, so parameters from one firmware or airframe must not be copied blindly.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><Card icon={Activity} title="Rate loop" text="Tracks commanded roll, pitch and yaw rotation rates. It is fast and fundamental to stabilisation."/><Card icon={Gauge} title="Attitude loop" text="Converts desired orientation into angular-rate targets for the inner loop."/><Card icon={BrainCircuit} title="Altitude/velocity loops" text="Use estimated vertical state to produce thrust and attitude targets where supported."/><Card icon={Compass} title="Position/navigation loops" text="Convert location or trajectory error into velocity, attitude and thrust demands."/></div></section>

  <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-center gap-3"><Vibrate className="text-amber-700"/><h3 className="text-2xl font-bold">Vibration and interference</h3></div><p className="mt-4 leading-8 text-slate-700">Unbalanced propellers, damaged bearings, flexible arms and poor mounting can inject vibration into IMU measurements. Overly soft isolation may introduce resonance instead of solving it. High-current wiring and magnetic materials can disturb compasses. Correct the physical source first, then use the flight stack&apos;s approved mounting, filtering and diagnostic guidance.</p><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Balance or replace propellers and inspect motors/bearings.", "Tighten the frame and repair cracks or flexible joints.", "Mount the controller in the documented orientation and method.", "Keep compass modules away from power distribution and high-current wiring.", "Review logs for clipping, vibration, estimator innovation and sensor-health warnings.", "Never mask a hardware defect by applying aggressive filters without diagnosis."].map(item=><li key={item} className="rounded-xl bg-white p-4">• {item}</li>)}</ul></section>

  <section><h3 className="text-2xl font-bold">Safe setup and calibration sequence</h3><ol className="mt-5 space-y-3">{["Remove propellers, restrain the aircraft and document the exact board, firmware and frame type.", "Set and verify flight-controller orientation before interpreting sensor motion.", "Calibrate the gyroscope while the aircraft is completely still as directed by the chosen firmware.", "Perform accelerometer calibration through every prompted orientation on a stable surface.", "Calibrate the compass away from motors, vehicles, steel structures and current-carrying wiring when the firmware requires it.", "Set the airframe/motor mapping and verify displayed roll, pitch and heading responses by moving the unpowered aircraft by hand.", "Review sensor health, estimator status, warnings and pre-arm checks; correct causes instead of disabling checks.", "Save a parameter backup and record firmware version, date, location and calibration result."].map((item,i)=><li key={item} className="flex gap-4 rounded-xl bg-slate-50 p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-600 text-sm font-bold text-white">{i+1}</span>{item}</li>)}</ol></section>

  <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-red-700"/><h3 className="text-2xl font-bold">Do not fly with unresolved warnings</h3></div><p className="mt-4 leading-8 text-slate-700">Estimator divergence, sensor inconsistency, calibration failure, excessive vibration, unexpected attitude display, incorrect board orientation or pre-arm faults can lead to immediate loss of control. Do not disable protection merely to make the aircraft arm. Diagnose the physical/configuration cause using official firmware documentation, logs and qualified supervision.</p></section>

  <section className="rounded-2xl bg-slate-900 p-6 text-white"><h3 className="text-2xl font-bold">Hands-on activity: controller data-flow and bench validation plan</h3><p className="mt-3 leading-7 text-slate-200">Draw a block diagram from sensors → estimator → attitude/rate controllers → mixer → ESCs/motors. Add pilot commands, navigation targets, logs and fail-safe inputs. Then prepare a propeller-free bench checklist that verifies board orientation, displayed roll/pitch/yaw direction, calibration status, receiver inputs, motor numbering, motor direction and estimator health. Explain which observation would stop the test at each stage.</p></section>
  <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-950">Chapter completion checklist</h3><p className="mt-3 leading-7 text-blue-900">Explain each core sensor, sketch the estimator/control data flow, complete the propeller-free bench plan, identify vibration and magnetic-interference controls, and score at least 80% below.</p></section>
</article><ChapterQuiz/></>}

function ChapterQuiz(){const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;const reset=()=>{setAnswers({});setSubmitted(false)};return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b border-slate-200 pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 4 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border border-slate-200 p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=answers[i]===j;const correct=submitted&&j===q.answer;const incorrect=submitted&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":incorrect?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"border-slate-200 hover:bg-slate-50"}`}><input type="radio" name={`drone-ch4-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(a=>({...a,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!submitted?<button type="button" disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button type="button" onClick={reset} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}
function Card({icon:Icon,title,text}){return <div className="rounded-2xl border border-slate-200 bg-white p-5">{Icon&&<Icon className="text-blue-600" size={26}/>}<h4 className={`${Icon?"mt-3":""} font-bold text-slate-900`}>{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
