import { useMemo, useState } from "react";
import { BatteryCharging, Cable, CheckCircle2, CircleHelp, Cpu, RotateCcw, ShieldAlert, Wrench, XCircle, Zap } from "lucide-react";

const questions = [
  { question: "What should be done before installing electronics on a new frame?", options: ["Fit the propellers", "Inspect alignment, fasteners, sharp edges and conductive contact risks", "Arm the aircraft", "Disable all warnings"], answer: 1 },
  { question: "Why should the flight controller orientation be documented?", options: ["It selects battery chemistry", "It changes motor KV", "The firmware must map controller axes to aircraft axes correctly", "It increases radio range"], answer: 2 },
  { question: "What is the purpose of a continuity check before first power-up?", options: ["Detect an unintended short across the power rails", "Calibrate GPS", "Bind the receiver", "Balance propellers"], answer: 0 },
  { question: "What does a smoke stopper or current-limited supply help with?", options: ["Increasing motor power", "Limiting damage if an assembly fault draws excessive current", "Programming flight modes", "Charging every battery type"], answer: 1 },
  { question: "How should signal and power wiring be routed?", options: ["Loose across propellers", "Directly over sharp carbon edges", "Securely, with strain relief and separation from interference where practical", "Twisted around hot motors"], answer: 2 },
  { question: "When should propellers be installed during initial configuration?", options: ["Only after all propeller-free checks are complete and flight testing is authorised", "Before receiver calibration", "Before motor mapping", "During firmware updates"], answer: 0 },
  { question: "What must a motor-output test verify?", options: ["Only motor colour", "Correct motor number and direction at low power with propellers removed", "Maximum thrust indoors", "GPS home position"], answer: 1 },
  { question: "Why create a configuration backup?", options: ["To increase battery capacity", "To replace inspection", "To preserve a known setup and support recovery or comparison", "To remove firmware warnings"], answer: 2 },
  { question: "What should happen if first power-up shows heat, smell or unexpected current?", options: ["Disconnect power immediately and investigate", "Increase current limit", "Install propellers", "Ignore it for one minute"], answer: 0 },
  { question: "What is the safest response to unresolved wiring or pre-arm faults?", options: ["Fly only in calm weather", "Raise throttle slowly", "Disable checks", "Do not fly until the cause is corrected"], answer: 3 },
];

export default function DroneChapterSixLesson() {
  return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
    <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 6</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Drone Assembly, Wiring and Pre-Flight Configuration</h2><p className="mt-4 leading-8 text-slate-600">Reliable flight begins at the workbench. Mechanical alignment, electrical integrity, component placement and software configuration must form one documented system. This chapter develops a controlled build process that finds faults before propellers or flight energy are introduced.</p></header>

    <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Plan a balanced frame layout and secure mechanical assembly.", "Route battery, motor, signal, receiver and peripheral wiring safely.", "Use polarity, resistance and continuity checks before first power-up.", "Perform a current-limited first-power inspection.", "Configure frame type, board orientation, receiver and motor outputs.", "Complete and document a propeller-free pre-flight acceptance test."].map(item=><li key={item} className="rounded-xl border border-slate-200 p-4"><b className="mr-2 text-emerald-600">✓</b>{item}</li>)}</ul></section>

    <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><Wrench className="text-blue-700"/><h3 className="text-2xl font-bold">Mechanical assembly</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card icon={Wrench} title="Frame and fasteners" text="Check arm orientation, cracks, thread engagement, motor-screw length and suitable thread locking where specified."/><Card icon={Cpu} title="Controller placement" text="Mount in the documented orientation near the intended centre, protected from vibration, impacts and conductive contact."/><Card icon={BatteryCharging} title="Mass distribution" text="Position the battery and payload so the centre of mass is practical and mounting straps cannot reach moving parts."/><Card icon={ShieldAlert} title="Clearances" text="Keep wires, antennas and accessories outside every propeller disk and away from sharp carbon or hot components."/></div><p className="mt-5 leading-7 text-slate-700">Never allow a motor screw to contact its windings. Confirm the motor maker&apos;s permitted screw depth instead of assuming all frame hardware is interchangeable.</p></section>

    <section><div className="flex items-center gap-3"><Cable className="text-indigo-700"/><h3 className="text-2xl font-bold">Power and signal wiring</h3></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Circuit</th><th className="p-3">Good practice</th><th className="p-3">Common risk</th></tr></thead><tbody className="divide-y"><tr><td className="p-3 font-semibold">Battery input</td><td className="p-3">Correct connector, polarity, wire gauge and insulated joints</td><td className="p-3">Reverse polarity or exposed conductor</td></tr><tr><td className="p-3 font-semibold">ESC/motor</td><td className="p-3">Short, secured paths with strain relief</td><td className="p-3">Chafing, poor soldering or loose phase wire</td></tr><tr><td className="p-3 font-semibold">Receiver/signals</td><td className="p-3">Correct voltage, port, protocol and signal ground</td><td className="p-3">Wrong pinout or electrical level</td></tr><tr><td className="p-3 font-semibold">GPS/compass</td><td className="p-3">Correct bus and separation from high current/magnets</td><td className="p-3">Interference or swapped connectors</td></tr></tbody></table></div><p className="mt-4 leading-8 text-slate-600">Use strain relief, grommets or edge protection where required. Secure cables without crushing insulation, leave service loops where appropriate, and keep high-current paths separated from sensitive signal and compass wiring as far as the design permits.</p></section>

    <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-center gap-3"><Zap className="text-amber-700"/><h3 className="text-2xl font-bold">Electrical inspection before power</h3></div><ol className="mt-5 space-y-3">{["Remove all propellers and disconnect the flight battery.", "Inspect every connector and solder joint under good light and magnification.", "Confirm battery polarity at the connector and power-distribution input with a meter.", "Check for unintended continuity or suspiciously low resistance across the main power rails.", "Confirm regulated-voltage outputs before attaching voltage-sensitive peripherals when the design allows.", "Perform first power-up through an appropriate current limiter or smoke stopper.", "Disconnect immediately if current, heat, smell, smoke, sound or indicator behaviour is unexpected."].map((item,i)=><li key={item} className="flex gap-4 rounded-xl bg-white p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-amber-600 text-sm font-bold text-white">{i+1}</span>{item}</li>)}</ol><p className="mt-4 text-sm leading-6 text-amber-900">A current limiter reduces risk but does not make incorrect wiring safe. Use instruments within their ratings, prevent probe slips and follow battery/fire precautions.</p></section>

    <section><h3 className="text-2xl font-bold">Pre-flight software configuration</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Firmware and airframe" text="Record the exact supported firmware, board target and frame geometry; avoid copying unrelated parameter files."/><Card title="Orientation and sensors" text="Verify the on-screen aircraft moves in the same direction as the physical frame before calibration."/><Card title="Radio and modes" text="Calibrate endpoints and direction, then confirm arming and mode-switch positions from Chapter 5."/><Card title="Motor mapping" text="With propellers removed, test each output individually at minimum practical power and confirm number and direction."/><Card title="Battery monitoring" text="Select the correct battery-monitor method and validate voltage/current readings against suitable instruments."/><Card title="Fail-safes and limits" text="Configure radio, battery and navigation responses deliberately and test the detectable conditions safely."/></div></section>

    <section className="rounded-2xl bg-indigo-50 p-6"><h3 className="text-2xl font-bold">Propeller-free acceptance sequence</h3><ol className="mt-5 grid gap-3 md:grid-cols-2">{["Board boots without unexpected resets or heat.", "Firmware identifies the intended sensors and peripherals.", "Displayed roll, pitch and yaw agree with hand movement.", "Receiver controls, endpoints and mode labels are correct.", "Every motor number and rotation direction matches the frame map.", "Battery voltage and warnings are plausible.", "Radio-loss and other detectable fail-safe states behave as documented.", "Logs show no unresolved sensor, estimator or power warnings."].map((item,i)=><li key={item} className="rounded-xl bg-white p-4"><b className="mr-2 text-indigo-700">{i+1}.</b>{item}</li>)}</ol></section>

    <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-red-700"/><h3 className="text-2xl font-bold">Stop conditions</h3></div><p className="mt-4 leading-8 text-slate-700">Reverse polarity, a short circuit, damaged insulation, loose hardware, excessive heat, incorrect controller orientation, unexpected motor response, unreliable receiver input, unexplained resets or unresolved pre-arm warnings are no-fly conditions. Disconnect safely, document the symptom and correct its root cause. Do not bypass checks merely to arm the aircraft.</p></section>

    <section className="rounded-2xl bg-slate-900 p-6 text-white"><h3 className="text-2xl font-bold">Hands-on activity: build record and acceptance sheet</h3><p className="mt-3 leading-7 text-slate-200">Create a labelled top-and-side layout showing component location, aircraft-forward direction, power paths, signal ports, antenna positions and motor numbering. Add a wiring table with connector, pinout, voltage and protocol. Complete a propeller-free acceptance sheet recording continuity, first-power current, sensor orientation, receiver channels, motor mapping, fail-safe results, firmware version and configuration-backup filename.</p></section>
    <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-950">Chapter completion checklist</h3><p className="mt-3 leading-7 text-blue-900">Produce the mechanical/electrical layout, pass continuity and current-limited power checks, complete the propeller-free acceptance sheet, save the configuration backup, resolve every stop condition, and score at least 80% below.</p></section>
  </article><ChapterQuiz/></>;
}

function ChapterQuiz(){const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;const reset=()=>{setAnswers({});setSubmitted(false)};return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b border-slate-200 pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 6 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border border-slate-200 p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=answers[i]===j;const correct=submitted&&j===q.answer;const incorrect=submitted&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":incorrect?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"border-slate-200 hover:bg-slate-50"}`}><input type="radio" name={`drone-ch6-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(a=>({...a,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!submitted?<button type="button" disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button type="button" onClick={reset} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}
function Card({icon:Icon,title,text}){return <div className="rounded-2xl border border-slate-200 bg-white p-5">{Icon&&<Icon className="text-blue-600" size={26}/>}<h4 className={`${Icon?"mt-3":""} font-bold text-slate-900`}>{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
