import { useMemo, useState } from "react";
import { Antenna, CheckCircle2, CircleHelp, Gamepad2, Radio, RotateCcw, ShieldAlert, SlidersHorizontal, XCircle } from "lucide-react";

const questions = [
  { question: "What is the main purpose of the RC radio link?", options: ["Charge the flight battery", "Carry pilot commands from the transmitter to the aircraft", "Measure propeller thrust", "Replace the flight controller"], answer: 1 },
  { question: "What is an auxiliary channel commonly used for?", options: ["Motor phase wiring", "Battery balancing", "A switch or knob such as flight-mode selection", "Changing propeller pitch mechanically"], answer: 2 },
  { question: "What does binding do?", options: ["Pairs a compatible transmitter and receiver", "Calibrates the accelerometer", "Balances the propellers", "Sets the home position"], answer: 0 },
  { question: "What should you do if a displayed control moves opposite to the stick?", options: ["Fly slowly and compensate", "Correct the channel direction and verify again with propellers removed", "Disable pre-arm checks", "Increase transmitter power"], answer: 1 },
  { question: "What is a benefit of a serial receiver protocol?", options: ["It eliminates the flight controller", "It powers the motors", "It carries multiple channels over a compact digital connection", "It guarantees unlimited range"], answer: 2 },
  { question: "Which antenna installation is generally best?", options: ["Clear of carbon, high-current wiring and strong RF sources", "Wrapped tightly around battery leads", "Inside a metal enclosure", "Touching the video transmitter antenna"], answer: 0 },
  { question: "What does a stabilised or angle mode normally provide?", options: ["No flight-controller assistance", "Attitude assistance such as self-levelling within configured limits", "Guaranteed obstacle avoidance", "Automatic battery charging"], answer: 1 },
  { question: "What must be valid before relying on Return-to-Launch?", options: ["Only the propeller colour", "Only transmitter battery percentage", "Home position, navigation estimate and configured RTL behaviour", "The camera memory card"], answer: 2 },
  { question: "How should radio-loss fail-safe first be tested?", options: ["On a restrained, propeller-free bench setup", "At maximum altitude", "During the first flight", "With all warnings disabled"], answer: 0 },
  { question: "What is the safest response to an unresolved channel, mode or fail-safe warning?", options: ["Increase throttle", "Use a larger battery", "Ignore it in calm weather", "Do not fly until it is understood and corrected"], answer: 3 },
];

export default function DroneChapterFiveLesson() {
  return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
    <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 5</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Radio Transmitters, Receivers and Flight Modes</h2><p className="mt-4 leading-8 text-slate-600">The radio system is the pilot&apos;s command path to the aircraft. A safe setup requires compatible hardware, correct channel mapping, reliable antenna installation, deliberate flight-mode choices, and a verified response when the link becomes weak or disappears.</p></header>

    <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Trace commands from transmitter controls to receiver and flight controller.", "Explain channels, binding, endpoints, centres and control direction.", "Compare PWM, PPM and common serial receiver links conceptually.", "Distinguish manual, stabilised, altitude, position and return modes.", "Configure arming and mode switches without unsafe ambiguity.", "Plan a propeller-free radio and signal-loss fail-safe test."].map(item=><li key={item} className="rounded-xl border border-slate-200 p-4"><b className="mr-2 text-emerald-600">✓</b>{item}</li>)}</ul></section>

    <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><Radio className="text-blue-700"/><h3 className="text-2xl font-bold">The command path</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card icon={Gamepad2} title="Transmitter" text="Converts sticks, switches and knobs into channel values and sends an encoded RF signal."/><Card icon={Antenna} title="Receiver" text="Decodes the link and delivers channel data, link quality and sometimes telemetry."/><Card icon={SlidersHorizontal} title="Flight controller" text="Maps channel values to pilot demands, arming logic, modes and auxiliary functions."/><Card icon={ShieldAlert} title="Fail-safe logic" text="Detects invalid or lost input and performs the action configured for the aircraft and operating area."/></div></section>

    <section><h3 className="text-2xl font-bold">Channels, binding and receiver connections</h3><p className="mt-4 leading-8 text-slate-600">Roll, pitch, yaw and throttle normally occupy four channels; switches and knobs use auxiliary channels. Binding securely associates compatible radio equipment. Receiver output may use individual PWM wires, combined PPM, or a digital serial protocol such as SBUS or CRSF. Confirm protocol, voltage, port, inversion requirements and firmware support in the manufacturers&apos; current documentation.</p><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Link</th><th className="p-3">Concept</th><th className="p-3">Setup concern</th></tr></thead><tbody className="divide-y"><tr><td className="p-3 font-semibold">PWM</td><td className="p-3">One signal connection per channel</td><td className="p-3">More wiring and correct channel order</td></tr><tr><td className="p-3 font-semibold">PPM</td><td className="p-3">Several channels combined in one pulse stream</td><td className="p-3">Compatibility and channel limits</td></tr><tr><td className="p-3 font-semibold">Serial bus</td><td className="p-3">Multiple digital channels on a compact link</td><td className="p-3">Correct UART/protocol, voltage and options</td></tr></tbody></table></div></section>

    <section className="rounded-2xl bg-indigo-50 p-6"><div className="flex items-center gap-3"><Antenna className="text-indigo-700"/><h3 className="text-2xl font-bold">Antenna placement and link health</h3></div><p className="mt-4 leading-8 text-slate-700">Keep receiver antennas clear of carbon fibre, metal, high-current wiring, motors and powerful video transmitters. Preserve the antenna manufacturer&apos;s active-element geometry and use diversity orientations where specified. Monitor RSSI, link quality, receiver voltage, packet loss and telemetry warnings; range-test using the radio maker&apos;s documented procedure before flight.</p></section>

    <section><h3 className="text-2xl font-bold">Input mapping and calibration</h3><ol className="mt-5 space-y-3">{["Remove every propeller, secure the aircraft and power the system using the documented method.", "Bind the transmitter and receiver, then confirm stable receiver power and link indication.", "In the ground station, verify roll, pitch, yaw and throttle respond to the intended controls.", "Correct direction, centre, minimum and maximum values; do not compensate for a reversed input while flying.", "Assign arming and flight modes to deliberate switches with clearly separated positions.", "Label the transmitter and verify each switch position aloud against the displayed mode.", "Check link-quality and low-radio-battery alerts, then save a configuration backup."].map((item,i)=><li key={item} className="flex gap-4 rounded-xl bg-slate-50 p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-600 text-sm font-bold text-white">{i+1}</span>{item}</li>)}</ol></section>

    <section><h3 className="text-2xl font-bold">Understanding flight modes</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Manual / rate / acro" text="Pilot inputs command rotation rates with little or no automatic levelling. It demands trained control skills."/><Card title="Stabilised / angle" text="The controller assists attitude control and commonly self-levels when sticks return toward centre."/><Card title="Altitude hold" text="Adds vertical-state control; performance depends on sensors, estimator quality and configuration."/><Card title="Position hold / loiter" text="Uses navigation estimates to hold location and requires suitable positioning data and environment."/><Card title="Return-to-Launch" text="Navigates using a valid home position and configured altitude/landing behaviour; it is not a universal rescue guarantee."/><Card title="Mission / autonomous" text="Follows programmed navigation and must be planned within regulations, aircraft limits and supervised contingencies."/></div><p className="mt-5 leading-7 text-slate-600">Names and exact behaviour vary by firmware. Read the active flight stack&apos;s documentation and validate mode transitions on the ground before relying on them.</p></section>

    <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-red-700"/><h3 className="text-2xl font-bold">Radio-loss fail-safe</h3></div><p className="mt-4 leading-8 text-slate-700">Receiver behaviour and flight-controller behaviour are separate layers: the receiver may hold values, output predefined values, or report link loss, while the controller must recognise the condition and choose an appropriate action. Never assume a default is safe. With propellers removed, verify the detected loss, delay, warning and configured response. Do not perform the first intentional loss-of-link test in the air, and do not choose RTL unless navigation, home, altitude and operating-area risks are understood.</p></section>

    <section className="rounded-2xl bg-slate-900 p-6 text-white"><h3 className="text-2xl font-bold">Hands-on activity: radio setup and mode card</h3><p className="mt-3 leading-7 text-slate-200">Create a channel map listing every stick, switch, channel number, minimum/centre/maximum value and assigned function. Add a mode card showing each switch position, required sensors and pilot escape action. Complete a propeller-free test of direction, endpoints, arming, mode indication, telemetry alerts and radio-loss detection. Record any result that would stop the aircraft from flying.</p></section>
    <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-950">Chapter completion checklist</h3><p className="mt-3 leading-7 text-blue-900">Explain the radio command path, complete a verified channel and mode map, document antenna placement, demonstrate the propeller-free fail-safe test plan, and score at least 80% below.</p></section>
  </article><ChapterQuiz/></>;
}

function ChapterQuiz(){const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;const reset=()=>{setAnswers({});setSubmitted(false)};return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b border-slate-200 pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 5 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border border-slate-200 p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=answers[i]===j;const correct=submitted&&j===q.answer;const incorrect=submitted&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":incorrect?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"border-slate-200 hover:bg-slate-50"}`}><input type="radio" name={`drone-ch5-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(a=>({...a,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!submitted?<button type="button" disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button type="button" onClick={reset} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}
function Card({icon:Icon,title,text}){return <div className="rounded-2xl border border-slate-200 bg-white p-5">{Icon&&<Icon className="text-blue-600" size={26}/>}<h4 className={`${Icon?"mt-3":""} font-bold text-slate-900`}>{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
