import { useMemo, useState } from "react";
import { Antenna, CheckCircle2, CircleHelp, Map, Monitor, RotateCcw, Satellite, ShieldAlert, XCircle } from "lucide-react";

const questions=[
 {question:"What does a GNSS receiver primarily provide to the flight controller?",options:["Motor phase current","Position, velocity and timing estimates","Propeller balance","Radio stick positions"],answer:1},
 {question:"Why is satellite count alone not enough to judge navigation quality?",options:["Geometry, signal quality, interference and estimator consistency also matter","All satellites are identical","Only battery voltage matters","It measures motor speed"],answer:0},
 {question:"Where should a GNSS/compass module generally be installed?",options:["Beside high-current battery leads","Under a motor","With a clear sky view and separation from interference sources","Inside a metal box"],answer:2},
 {question:"What is telemetry?",options:["A propeller measurement","A data link carrying aircraft status, commands or messages","A battery chemistry","A frame geometry"],answer:1},
 {question:"What is a ground control station used for?",options:["Replacing every pilot decision","Monitoring, configuration, logs and mission planning where authorised","Charging motors","Balancing airframes"],answer:1},
 {question:"What should be verified before accepting the home position?",options:["Valid navigation status and a plausible map location","Only the frame colour","Maximum throttle","Camera resolution"],answer:0},
 {question:"What is the safest response to a map position that jumps or disagrees with reality?",options:["Start an autonomous mission","Increase altitude","Do not rely on navigation modes until the cause is resolved","Disable warnings"],answer:2},
 {question:"Why should telemetry-loss behaviour be planned?",options:["Loss of the ground-station link may not equal loss of RC control, but monitoring or commands may disappear","It increases propeller efficiency","It changes motor KV","It guarantees RTL"],answer:0},
 {question:"What information should be protected when sharing flight logs?",options:["Only motor colour","Personal, location, identifier and operational data","Propeller diameter only","Nothing; logs contain no sensitive data"],answer:1},
 {question:"What is the safest response to unresolved GNSS, compass or estimator warnings?",options:["Fly only in position hold","Ignore them below 10 metres","Use more throttle","Do not fly navigation-dependent modes until corrected"],answer:3},
];

export default function DroneChapterEightLesson(){return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
 <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 8</p><h2 className="mt-2 text-3xl font-bold text-slate-900">GPS, Telemetry and Ground Control Stations</h2><p className="mt-4 leading-8 text-slate-600">Navigation depends on more than a dot on a map. The aircraft combines satellite navigation with inertial and other sensors, while telemetry and a ground control station help the operator inspect health, configure the vehicle and review evidence. Every link must be understood, checked and used within applicable aviation and privacy rules.</p></header>
 <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Explain GNSS position, velocity, timing and common error sources.","Interpret fix status, accuracy indicators and estimator consistency.","Plan GNSS, compass and antenna installation to reduce interference.","Describe telemetry links, data rates, range and loss-of-link effects.","Use a ground control station for health checks, configuration and logs.","Create a safe navigation-readiness and data-privacy checklist."].map(x=><li key={x} className="rounded-xl border border-slate-200 p-4"><b className="mr-2 text-emerald-600">✓</b>{x}</li>)}</ul></section>
 <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><Satellite className="text-blue-700"/><h3 className="text-2xl font-bold">GNSS positioning fundamentals</h3></div><p className="mt-4 leading-8 text-slate-700">A GNSS receiver estimates position and time from signals transmitted by multiple satellite constellations. The flight controller normally fuses these measurements with inertial sensors and may use barometer, compass or other aids. Buildings, terrain, foliage, reflections, interference and poor satellite geometry can degrade or bias a solution even when several satellites are visible.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Fix and validity" text="Confirm the flight stack reports a usable solution, not merely receiver power or detected satellites."/><Card title="Accuracy and geometry" text="Review the available horizontal/vertical uncertainty, dilution or equivalent quality indicators."/><Card title="Consistency" text="Check that position, velocity and heading agree with the stationary aircraft and estimator."/><Card title="Home position" text="Accept home only when the displayed location and altitude reference are plausible for the operating plan."/></div></section>
 <section><div className="flex items-center gap-3"><Antenna className="text-indigo-700"/><h3 className="text-2xl font-bold">Installation and interference control</h3></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Element</th><th className="p-3">Installation goal</th><th className="p-3">Risk to avoid</th></tr></thead><tbody className="divide-y"><tr><td className="p-3 font-semibold">GNSS antenna</td><td className="p-3">Clear view of the sky in its specified orientation</td><td className="p-3">Shielding, damaged coax or strong RF interference</td></tr><tr><td className="p-3 font-semibold">Compass</td><td className="p-3">Known orientation away from motors and high current</td><td className="p-3">Magnetic bias that changes with throttle</td></tr><tr><td className="p-3 font-semibold">Telemetry antenna</td><td className="p-3">Documented orientation and separation</td><td className="p-3">Blocked radiation, mismatched antenna or unsafe RF exposure</td></tr><tr><td className="p-3 font-semibold">Cabling</td><td className="p-3">Secure, strain-relieved and correct port/voltage</td><td className="p-3">Noise coupling, loose connectors or wrong pinout</td></tr></tbody></table></div></section>
 <section className="rounded-2xl bg-indigo-50 p-6"><div className="flex items-center gap-3"><Monitor className="text-indigo-700"/><h3 className="text-2xl font-bold">Telemetry and ground control stations</h3></div><p className="mt-4 leading-8 text-slate-700">Telemetry may carry aircraft state, warnings, parameters, mission data and operator commands over a radio, Wi-Fi, cellular or wired link. A ground control station presents this information for configuration, planning, monitoring and log review. Link frequency, power, encryption, antenna use and operation must comply with local rules and equipment approvals.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Status dashboard" text="Monitor mode, arming state, position quality, battery, radio, estimator and active warnings."/><Card title="Parameter management" text="Read documentation, change deliberately, compare versions and save backups before flight."/><Card title="Map and planning" text="Confirm map datum, terrain, route, altitude references, airspace and launch/recovery area."/><Card title="Logs and evidence" text="Download, label and preserve logs so warnings and flight behaviour can be traced after testing."/></div></section>
 <section><h3 className="text-2xl font-bold">Navigation-readiness workflow</h3><ol className="mt-5 space-y-3">{["Work outdoors in an authorised clear area; keep propellers removed during configuration.","Confirm firmware, GNSS/compass type, port, voltage, protocol and physical orientation.","Power the aircraft away from interference and allow the navigation solution to settle.","Compare the ground-station map position, altitude, speed and heading with physical reality.","Review fix status, uncertainty/quality, estimator health and compass consistency—not satellite count alone.","Verify home location and the configured action for GNSS, telemetry, radio and battery failures.","Check telemetry range indication, warnings and what control remains if the ground-station link is lost.","Save configuration and a readiness record; install propellers only after all other checks and authorisation."].map((x,i)=><li key={x} className="flex gap-4 rounded-xl bg-slate-50 p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-600 text-sm font-bold text-white">{i+1}</span>{x}</li>)}</ol></section>
 <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-center gap-3"><Map className="text-amber-700"/><h3 className="text-2xl font-bold">Maps, altitude and situational awareness</h3></div><p className="mt-4 leading-8 text-slate-700">Map imagery may be old or inaccurate and cannot prove airspace permission or obstacle clearance. Altitude values may use different references, while terrain and structures change. The operator must reconcile the ground station with current official airspace information, local survey/terrain knowledge, visual observation and the mission&apos;s documented altitude reference.</p></section>
 <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-red-700"/><h3 className="text-2xl font-bold">Navigation and data stop conditions</h3></div><p className="mt-4 leading-8 text-slate-700">Do not use navigation-dependent modes when position jumps, velocity appears while stationary, heading is implausible, home is wrong, accuracy is inadequate, the estimator rejects measurements, interference warnings appear or required maps/airspace data are uncertain. Flight logs can reveal home addresses, routes, identifiers and operating patterns; store and share them with appropriate access control and redaction.</p></section>
 <section className="rounded-2xl bg-slate-900 p-6 text-white"><h3 className="text-2xl font-bold">Hands-on activity: GCS readiness report</h3><p className="mt-3 leading-7 text-slate-200">With propellers removed, create a ground-station report containing connection method, firmware, GNSS/compass status, displayed location/heading, accuracy indicators, home position, battery and radio health, telemetry-loss observation, warnings and configuration-backup filename. Add screenshots only after removing personal location and identifier data. Conclude with a clear GO/NO-GO decision and reasons.</p></section>
 <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-950">Chapter completion checklist</h3><p className="mt-3 leading-7 text-blue-900">Explain GNSS quality beyond satellite count, document installation, verify the GCS navigation-readiness workflow, identify telemetry-loss effects, protect sensitive log data, make a justified GO/NO-GO decision, and score at least 80% below.</p></section>
</article><ChapterQuiz/></>}

function ChapterQuiz(){const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;const reset=()=>{setAnswers({});setSubmitted(false)};return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b border-slate-200 pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 8 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border border-slate-200 p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=answers[i]===j;const correct=submitted&&j===q.answer;const incorrect=submitted&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":incorrect?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"border-slate-200 hover:bg-slate-50"}`}><input type="radio" name={`drone-ch8-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(a=>({...a,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!submitted?<button type="button" disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button type="button" onClick={reset} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}
function Card({title,text}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><h4 className="font-bold text-slate-900">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
