import { useMemo, useState } from "react";
import { BatteryCharging, CheckCircle2, CircleHelp, Cable, Gauge, RotateCcw, ShieldAlert, Thermometer, Wind, XCircle, Zap } from "lucide-react";

const questions = [
  { question: "What does an ESC do in a brushless propulsion system?", options: ["Electronically commutates and controls motor speed", "Measures GPS position", "Balances the airframe", "Stores video"], answer: 0 },
  { question: "What does a motor's KV rating approximately describe?", options: ["No-load revolutions per minute per volt", "Battery capacity in amp-hours", "Maximum frame mass", "Propeller diameter"], answer: 0 },
  { question: "Why must motor, propeller, voltage and ESC be evaluated as one system?", options: ["Their combination determines current, thrust, heat and safe limits", "They determine airspace colour", "They replace the flight controller", "They set GPS accuracy"], answer: 0 },
  { question: "What does the S value of a LiPo battery identify?", options: ["Number of cells connected in series", "Storage time in seconds", "Number of motors", "Propeller pitch"], answer: 0 },
  { question: "What is electrical power in a DC system approximately equal to?", options: ["Voltage multiplied by current", "Voltage divided by time", "Capacity multiplied by frame size", "KV divided by propeller diameter"], answer: 0 },
  { question: "Why should an ESC have current margin above measured maximum demand?", options: ["Real loads, cooling and transients can differ from ideal test values", "It increases GPS satellites", "It changes frame geometry", "It balances battery cells"], answer: 0 },
  { question: "What is the purpose of a LiPo balance connector?", options: ["Allow monitoring and balancing of individual cell voltages", "Power the receiver directly in every design", "Change motor direction", "Measure propeller thrust"], answer: 0 },
  { question: "What should be done with a swollen or physically damaged LiPo battery?", options: ["Stop using it, isolate it safely and follow qualified disposal guidance", "Puncture it", "Charge it unattended", "Fit a larger propeller"], answer: 0 },
  { question: "What is the safest condition for checking motor direction?", options: ["Propellers removed and the airframe restrained", "Aircraft held above the head", "Full throttle with spectators nearby", "Damaged propellers installed"], answer: 0 },
  { question: "Why are connector and wire ratings important?", options: ["Undersized conductors can overheat, lose voltage or fail", "They determine legal altitude", "They calibrate the IMU", "They replace fuses"], answer: 0 },
];

export default function DroneChapterThreeLesson(){return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
  <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 3</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Brushless Motors, ESCs, Propellers and Power Systems</h2><p className="mt-4 leading-8 text-slate-600">A reliable drone propulsion system is a matched electrical, mechanical and aerodynamic system. This chapter explains how the battery, wiring, ESC, brushless motor and propeller interact, how to estimate energy and current demand, and how to reject unsafe component combinations before flight.</p></header>

  <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Explain brushless motor construction and electronic commutation.", "Interpret motor KV, voltage, current and manufacturer test data.", "Describe ESC ratings, signal input, firmware and cooling needs.", "Relate propeller diameter and pitch to load, thrust and efficiency.", "Estimate pack voltage, energy, current demand and flight-time limits.", "Apply safe LiPo charging, inspection, storage and isolation practices."].map(item=><li key={item} className="rounded-xl border border-slate-200 p-4"><b className="mr-2 text-emerald-600">✓</b>{item}</li>)}</ul></section>

  <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><Zap className="text-blue-700"/><h3 className="text-2xl font-bold">Brushless motor fundamentals</h3></div><p className="mt-4 leading-8 text-slate-700">A brushless DC motor contains permanent magnets on the rotor and windings on the stator. Because it has no mechanical brushes to switch current, an ESC energises the motor phases in sequence. Swapping any two of the three phase wires reverses direction on many conventional systems, but direction must always be checked with propellers removed.</p><div className="mt-5 grid gap-4 md:grid-cols-3"><Card title="KV rating" text="Approximate no-load rpm per volt. It is not a direct power or quality rating, and loaded speed is lower."/><Card title="Torque and heat" text="The propeller load demands torque and current. Excess load raises winding, ESC and battery temperature."/><Card title="Manufacturer data" text="Use verified thrust-stand tables for the exact motor, voltage and propeller rather than guessing from KV alone."/></div></section>

  <section><div className="flex items-center gap-3"><Gauge className="text-indigo-700"/><h3 className="text-2xl font-bold">Electronic speed controllers</h3></div><p className="mt-4 leading-8 text-slate-600">The ESC converts battery DC into timed three-phase motor drive and interprets a command from the flight controller. Compatibility includes battery voltage, continuous and short-duration current, signal protocol, firmware, motor timing, connector quality and cooling.</p><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">ESC item</th><th className="p-3">Why it matters</th><th className="p-3">Verification</th></tr></thead><tbody className="divide-y"><tr><td className="p-3 font-semibold">Voltage range</td><td className="p-3">Components must tolerate the pack&apos;s full charged voltage</td><td className="p-3">Check the exact cell-count specification</td></tr><tr><td className="p-3 font-semibold">Current rating</td><td className="p-3">Insufficient margin may overheat or damage the ESC</td><td className="p-3">Compare measured worst-case current and cooling conditions</td></tr><tr><td className="p-3 font-semibold">Signal protocol</td><td className="p-3">Determines command compatibility and update behaviour</td><td className="p-3">Match flight-controller output and ESC firmware</td></tr><tr><td className="p-3 font-semibold">Telemetry</td><td className="p-3">May report current, voltage, rpm or temperature</td><td className="p-3">Confirm wiring and firmware support</td></tr></tbody></table></div></section>

  <section className="rounded-2xl bg-sky-50 p-6"><div className="flex items-center gap-3"><Wind className="text-sky-700"/><h3 className="text-2xl font-bold">Propeller diameter, pitch and direction</h3></div><p className="mt-4 leading-8 text-slate-700">Diameter describes the swept size; pitch is a geometric indicator of theoretical forward advance per revolution. Increasing either can increase aerodynamic load and current, so a physically fitting propeller is not automatically electrically safe. Match clockwise/counter-clockwise type, mounting method and rotation direction to the motor map.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Larger diameter" text="Usually sweeps more air and may produce efficient thrust at lower rpm, but increases clearance and torque requirements."/><Card title="Higher pitch" text="Can favour faster airflow but often increases load. Actual performance depends on the complete system and operating point."/><Card title="Blade count" text="Additional blades may add thrust within a limited diameter but change efficiency, current, vibration and noise."/><Card title="Balance and condition" text="Reject cracked, chipped, deformed or poorly fitting propellers; imbalance transmits vibration to sensors and structure."/></div></section>

  <section><div className="flex items-center gap-3"><BatteryCharging className="text-emerald-700"/><h3 className="text-2xl font-bold">LiPo packs: voltage, capacity and energy</h3></div><p className="mt-4 leading-8 text-slate-600">Cells connected in series increase pack voltage; capacity is commonly expressed in milliamp-hours. A rough stored-energy comparison uses watt-hours: <b>nominal voltage × amp-hours</b>. Capacity does not equal safe current by itself, and printed discharge claims must be treated cautiously and validated against trusted specifications and testing.</p><div className="mt-5 grid gap-4 md:grid-cols-3"><Formula title="Nominal pack voltage" value="cell nominal voltage × series count"/><Formula title="Energy estimate" value="nominal volts × amp-hours = watt-hours"/><Formula title="Electrical power" value="volts × amps = watts"/></div><div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-5"><h4 className="font-bold text-emerald-950">Illustrative energy calculation</h4><p className="mt-2 leading-7 text-emerald-900">A pack marked 14.8 V nominal and 5,000 mAh (5 Ah) stores approximately 14.8 × 5 = 74 Wh under nominal assumptions. Usable flight energy is lower because safe voltage limits, load, temperature, ageing and reserve requirements matter.</p></div></section>

  <section><div className="flex items-center gap-3"><Cable className="text-blue-700"/><h3 className="text-2xl font-bold">Power distribution and wiring</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Current path" text="Battery connector, distribution board or harness, ESC leads and solder joints must safely carry the expected current."/><Card title="Voltage drop" text="Long, thin or poor-quality conductors and connectors waste power as heat and reduce voltage available to the system."/><Card title="Polarity and insulation" text="Reverse polarity can destroy electronics. Insulate joints, add strain relief and prevent abrasion against carbon-fibre edges."/><Card title="Protection and serviceability" text="Use appropriate protection, secure cables away from propellers, and design connectors so inspection and maintenance are possible."/></div></section>

  <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-red-700"/><h3 className="text-2xl font-bold">LiPo fire and handling safety</h3></div><ul className="mt-4 space-y-2 text-slate-700"><li>• Use a compatible balance charger and the battery manufacturer&apos;s voltage/current instructions.</li><li>• Charge in a suitable non-combustible area under continuous supervision; keep an appropriate emergency plan available.</li><li>• Protect terminals from short circuit and packs from puncture, crushing, heat, moisture and conductive tools.</li><li>• Stop using a pack that is swollen, damaged, leaking, unusually hot or behaving abnormally; isolate it without unnecessary handling.</li><li>• Follow qualified local hazardous-battery recycling/disposal guidance—never puncture, burn or place a damaged pack in normal waste.</li><li>• After a crash, disconnect power only if safe, move people away and monitor the battery for delayed heating or swelling.</li></ul></section>

  <section className="rounded-2xl bg-amber-50 p-6"><div className="flex items-center gap-3"><Thermometer className="text-amber-700"/><h3 className="text-2xl font-bold">Safe propulsion validation sequence</h3></div><ol className="mt-4 space-y-3">{["Document all component part numbers, ratings and connector types.", "Review manufacturer test data for the exact voltage and propeller combination.", "Calculate expected total current and ensure battery, wiring and ESC margin.", "Inspect soldering, insulation, polarity, strain relief and cooling paths.", "With propellers removed, test flight-controller motor assignment and rotation at the lowest practical command.", "Use a rated, guarded thrust stand only under qualified supervision for loaded measurement.", "Record current, voltage, thrust and temperature; stop immediately at any abnormal sound, smell, vibration or heat."].map((item,i)=><li key={item} className="flex gap-4 rounded-xl bg-white p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-amber-600 text-sm font-bold text-white">{i+1}</span>{item}</li>)}</ol></section>

  <section className="rounded-2xl bg-slate-900 p-6 text-white"><h3 className="text-2xl font-bold">Hands-on design activity</h3><p className="mt-3 leading-7 text-slate-200">Prepare a propulsion-selection worksheet for the Chapter 2 paper quadcopter. Choose a hypothetical motor, ESC, propeller and battery using published test data. Record pack voltage, per-motor current and thrust at two operating points; calculate total current, estimated electrical power and thrust-to-weight ratio; then identify the weakest rating in the current path. Finish with five reasons the selection must still be physically tested by qualified personnel before flight.</p></section>
  <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-950">Chapter completion checklist</h3><p className="mt-3 leading-7 text-blue-900">Explain motor/ESC commutation, interpret KV without treating it as power, calculate voltage/energy/power examples, complete the propulsion worksheet, demonstrate LiPo safety decisions, and score at least 80% below.</p></section>
</article><ChapterQuiz/></>}

function ChapterQuiz(){const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;const reset=()=>{setAnswers({});setSubmitted(false)};return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b border-slate-200 pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 3 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border border-slate-200 p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=answers[i]===j;const correct=submitted&&j===q.answer;const incorrect=submitted&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":incorrect?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"border-slate-200 hover:bg-slate-50"}`}><input type="radio" name={`drone-ch3-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(a=>({...a,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!submitted?<button type="button" disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button type="button" onClick={reset} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}
function Card({title,text}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><h4 className="font-bold text-slate-900">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
function Formula({title,value}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><h4 className="font-bold text-emerald-800">{title}</h4><p className="mt-3 font-mono text-sm text-slate-700">{value}</p></div>}
