import { useMemo, useState } from "react";
import { Activity, CheckCircle2, CircleHelp, Gauge, RotateCcw, ShieldAlert, SlidersHorizontal, TestTube2, XCircle } from "lucide-react";

const questions = [
  { question: "Why must sensor and radio calibration be completed before tuning?", options: ["Tuning can only work from trustworthy measurements and commands", "It increases battery capacity", "It changes propeller material", "It guarantees GPS reception"], answer: 0 },
  { question: "What does the proportional term mainly respond to?", options: ["Accumulated historical error only", "The present control error", "Battery voltage only", "GPS satellite count"], answer: 1 },
  { question: "What is the integral term commonly used to correct?", options: ["Short radio packets", "Camera focus", "Persistent bias or steady-state error", "Propeller colour"], answer: 2 },
  { question: "What does the derivative term generally react to?", options: ["How rapidly error or motion is changing", "Only vehicle mass", "Home position", "Battery chemistry"], answer: 0 },
  { question: "What may rapid high-frequency oscillation indicate?", options: ["Perfect tuning", "Excessive gain, noise, vibration or related control problems", "A full battery", "Correct GPS home"], answer: 1 },
  { question: "How should tuning changes normally be made?", options: ["Change every parameter together", "Copy values from any drone", "Use small documented changes with one controlled variable at a time", "Disable logging"], answer: 2 },
  { question: "Where should an initial hover test be performed?", options: ["In a clear authorised area with separation, suitable weather and an observer where required", "Above people", "Inside a crowded room", "Near power lines"], answer: 0 },
  { question: "What is a useful post-flight diagnostic source?", options: ["Frame colour", "Flight logs showing targets, response, vibration and saturation", "Only pilot memory", "Propeller packaging"], answer: 1 },
  { question: "What should a pilot do after unexpected oscillation or loss of control margin?", options: ["Land safely, disarm and investigate before another flight", "Increase gains immediately in flight", "Continue until the battery is empty", "Disable fail-safes"], answer: 0 },
  { question: "What is the safest response to unresolved vibration, estimator or control warnings?", options: ["Fly lower", "Use a larger battery", "Ignore them in stabilised mode", "Do not fly until the cause is corrected"], answer: 3 },
];

export default function DroneChapterSevenLesson(){return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
  <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 7</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Calibration, PID Tuning and Safe Flight Testing</h2><p className="mt-4 leading-8 text-slate-600">A drone should be tuned only after its mechanical build, sensors, radio, motor mapping and fail-safes are verified. Tuning is a measured engineering process: define a baseline, change one controlled variable, observe the response, inspect logs and keep a safe route back to the last known configuration.</p></header>

  <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Explain why calibration and mechanical health precede PID tuning.", "Describe proportional, integral and derivative actions conceptually.", "Recognise sluggish response, overshoot, oscillation and actuator saturation.", "Plan small, reversible and documented tuning changes.", "Design a staged ground, hover and low-risk flight-test programme.", "Use logs and stop criteria to make evidence-based decisions."].map(item=><li key={item} className="rounded-xl border border-slate-200 p-4"><b className="mr-2 text-emerald-600">✓</b>{item}</li>)}</ul></section>

  <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><Gauge className="text-blue-700"/><h3 className="text-2xl font-bold">Establish a trustworthy baseline</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Mechanical health" text="Balanced undamaged propellers, sound bearings, rigid frame, correct fasteners and no loose payloads."/><Card title="Sensor health" text="Correct orientation and calibration, acceptable vibration, consistent estimator state and no clipping."/><Card title="Control inputs" text="Correct channel directions, centres, endpoints, mode switches and radio-loss response."/><Card title="Actuation" text="Correct motor order/direction, suitable propellers, ESC configuration and adequate thrust margin."/></div><p className="mt-5 leading-7 text-slate-700">Save the working parameters and record firmware, payload, propellers, battery, centre of mass and weather. A tune belongs to a specific aircraft configuration; copying numbers from a different build may be unsafe.</p></section>

  <section><div className="flex items-center gap-3"><SlidersHorizontal className="text-indigo-700"/><h3 className="text-2xl font-bold">PID control in practical terms</h3></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Term</th><th className="p-3">Responds to</th><th className="p-3">Too little may show</th><th className="p-3">Too much may show</th></tr></thead><tbody className="divide-y"><tr><td className="p-3 font-semibold">P</td><td className="p-3">Present error</td><td className="p-3">Soft or inaccurate tracking</td><td className="p-3">Overshoot or oscillation</td></tr><tr><td className="p-3 font-semibold">I</td><td className="p-3">Accumulated error</td><td className="p-3">Persistent bias under load/disturbance</td><td className="p-3">Slow oscillation or windup effects</td></tr><tr><td className="p-3 font-semibold">D</td><td className="p-3">Rate of change</td><td className="p-3">Less damping</td><td className="p-3">Noise sensitivity, heat or high-frequency activity</td></tr></tbody></table></div><p className="mt-4 leading-8 text-slate-600">Modern flight stacks add feed-forward, filters, limits and specialised controllers. Parameter names and interactions differ. Use the exact firmware&apos;s current tuning procedure rather than treating this table as universal parameter instructions.</p></section>

  <section className="rounded-2xl bg-indigo-50 p-6"><div className="flex items-center gap-3"><Activity className="text-indigo-700"/><h3 className="text-2xl font-bold">Reading aircraft response</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Sluggish tracking" text="Commanded motion is followed slowly; also check thrust margin, limits, filtering and mechanical drag before changing gains."/><Card title="Overshoot" text="Response passes the target and returns; distinguish control tuning from flexible structure or pilot input."/><Card title="Rapid oscillation" text="May indicate excessive gain, vibration, noise, delay or resonance. Land and diagnose instead of continuing."/><Card title="Saturation" text="Motors reach output limits, reducing control authority. Check payload, battery, propellers, centre of mass and manoeuvre demand."/></div></section>

  <section><h3 className="text-2xl font-bold">Controlled tuning workflow</h3><ol className="mt-5 space-y-3">{["Confirm the Chapter 6 acceptance sheet and resolve every warning.", "Back up parameters and define the single behaviour to improve.", "Select the flight stack&apos;s documented tuning or auto-tune method and prerequisites.", "Choose a clear authorised test area, suitable weather, trained pilot, observer and emergency plan.", "Make one small, documented and reversible change—or run the approved automated routine.", "Fly a short repeatable test within conservative limits, then land and disarm.", "Review pilot observations and logs before deciding whether to keep, revise or revert the change.", "Repeat only while stop criteria, battery margin and environmental conditions remain acceptable."].map((item,i)=><li key={item} className="flex gap-4 rounded-xl bg-slate-50 p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-600 text-sm font-bold text-white">{i+1}</span>{item}</li>)}</ol></section>

  <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-center gap-3"><TestTube2 className="text-amber-700"/><h3 className="text-2xl font-bold">Staged flight testing</h3></div><div className="mt-5 grid gap-3 md:grid-cols-2">{["Ground: arming logic, mode indication and fail-safe detection with propellers removed.", "Initial lift: brief low hover with a prepared immediate-land decision.", "Basic response: gentle roll, pitch, yaw and altitude inputs in stabilised modes.", "Disturbance response: only approved modest tests with ample separation and recovery margin.", "Mode expansion: introduce one new mode only after its prerequisites and escape mode are confirmed.", "Endurance: monitor voltage, current, temperature and remaining landing reserve."].map((item,i)=><div key={item} className="rounded-xl bg-white p-4"><b className="mr-2 text-amber-700">{i+1}.</b>{item}</div>)}</div></section>

  <section><h3 className="text-2xl font-bold">Use logs, not guesswork</h3><p className="mt-4 leading-8 text-slate-600">Compare commanded and measured angular rates, actuator outputs, vibration, clipping, estimator status, battery voltage/current and mode/fail-safe events. Look for repeatable evidence rather than changing parameters from a single impression. Preserve each flight&apos;s parameter snapshot and test notes so results remain traceable.</p></section>

  <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-red-700"/><h3 className="text-2xl font-bold">Immediate stop criteria</h3></div><p className="mt-4 leading-8 text-slate-700">Land and disarm for rapid oscillation, unexpected attitude, control reversal, unreliable radio, estimator or sensor warnings, abnormal sound, excessive motor/ESC heat, structural looseness, battery sag, unexpected mode change, people or aircraft entering the area, or deteriorating weather. Do not suppress warnings or continue tuning to “see if it improves.”</p></section>

  <section className="rounded-2xl bg-slate-900 p-6 text-white"><h3 className="text-2xl font-bold">Hands-on activity: safe test card and tuning log</h3><p className="mt-3 leading-7 text-slate-200">Prepare a one-page test card listing objective, baseline configuration, site/weather limits, crew roles, flight mode, manoeuvre, altitude/area boundary, battery reserve, immediate-land conditions and emergency response. Create a tuning log with parameter before/after values, flight-log filename, observation, measured result and keep/revert decision. Conduct only simulations or authorised supervised tests appropriate to your competence.</p></section>
  <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-950">Chapter completion checklist</h3><p className="mt-3 leading-7 text-blue-900">Explain P, I and D actions, verify the baseline gates, prepare the flight-test card, demonstrate a traceable one-change tuning record, identify log evidence and stop criteria, and score at least 80% below.</p></section>
</article><ChapterQuiz/></>}

function ChapterQuiz(){const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;const reset=()=>{setAnswers({});setSubmitted(false)};return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b border-slate-200 pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 7 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border border-slate-200 p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=answers[i]===j;const correct=submitted&&j===q.answer;const incorrect=submitted&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":incorrect?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"border-slate-200 hover:bg-slate-50"}`}><input type="radio" name={`drone-ch7-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(a=>({...a,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!submitted?<button type="button" disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button type="button" onClick={reset} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}
function Card({title,text}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><h4 className="font-bold text-slate-900">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
