import { useMemo, useState } from "react";
import { CheckCircle2, CircleHelp, ClipboardCheck, FileCheck2, Plane, RotateCcw, ShieldAlert, TestTube2, Wrench, XCircle } from "lucide-react";

const questions=[
 {question:"What should the capstone project begin with?",options:["A written requirement, operating limits and acceptance criteria","Installing propellers","Maximum-throttle testing","Copying another drone's parameters"],answer:0},
 {question:"Why is a power budget required?",options:["To choose frame colour","To verify components, current paths, battery and endurance are compatible","To replace flight tests","To increase GPS satellites"],answer:1},
 {question:"What is the purpose of a design review before assembly?",options:["Make the report longer","Identify incompatibilities and hazards before hardware is energised","Disable checks","Select a social-media image"],answer:1},
 {question:"When should propellers remain removed?",options:["Only during painting","During wiring, configuration, receiver, sensor and motor-output verification","Only after landing","Never"],answer:1},
 {question:"What is required before the first hover?",options:["A completed acceptance checklist with all critical faults resolved","Only a GNSS fix","Only a charged battery","A long autonomous mission"],answer:0},
 {question:"How should flight capability be expanded?",options:["All modes in one flight","One tested step at a time with defined stop criteria","Above people for observation","Without logs"],answer:1},
 {question:"What makes capstone evidence traceable?",options:["Only photographs","Versioned configuration, checklists, logs, test results and decisions","Pilot memory","Propeller packaging"],answer:1},
 {question:"What should happen if measured performance misses an acceptance criterion?",options:["Hide the result","Increase every gain","Analyse the cause, correct or revise safely, and retest the affected gate","Issue the certificate anyway"],answer:2},
 {question:"What is the purpose of a post-flight inspection?",options:["Find damage, looseness, heat and logged anomalies before the next flight","Charge the transmitter","Change airspace permission","Replace mission planning"],answer:0},
 {question:"What is the safest response to an unresolved critical defect?",options:["Fly a shorter mission","Ask the autopilot to compensate","Disable the warning","Do not fly until it is corrected and reverified"],answer:3},
];

export default function DroneChapterTenLesson(){return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
 <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 10 • Final Project</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Build and Test a GPS Quadcopter</h2><p className="mt-4 leading-8 text-slate-600">The capstone converts course knowledge into an engineering record. Learners design a GPS-equipped quadcopter, justify component choices, assemble and configure it, pass propeller-free verification, conduct authorised staged tests and present evidence that every safety and performance claim is supported.</p></header>
 <section><h3 className="text-2xl font-bold">Project outcomes</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Translate an operational objective into measurable requirements.","Produce architecture, component, power, wiring and risk documents.","Build and configure the aircraft with traceable quality checks.","Verify sensors, controls, motors, navigation and fail-safes safely.","Plan and execute staged tests with explicit stop conditions.","Present results, limitations, logs and improvement recommendations."].map(x=><li key={x} className="rounded-xl border border-slate-200 p-4"><b className="mr-2 text-emerald-600">✓</b>{x}</li>)}</ul></section>
 <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><ClipboardCheck className="text-blue-700"/><h3 className="text-2xl font-bold">1. Define the project</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Mission statement" text="Describe the training task, authorised environment, operator, payload and expected flight functions."/><Card title="Measurable criteria" text="Set conservative limits for mass, hover time, controllability, navigation quality, link health and landing reserve."/><Card title="Constraints" text="Record budget, available parts, competence, site, weather, airspace, privacy and supervision requirements."/><Card title="No-fly criteria" text="Define critical faults, environmental limits and documentation gaps that prevent testing."/></div></section>
 <section><div className="flex items-center gap-3"><Plane className="text-indigo-700"/><h3 className="text-2xl font-bold">2. Design package</h3></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Deliverable</th><th className="p-3">Minimum content</th></tr></thead><tbody className="divide-y"><tr><td className="p-3 font-semibold">System architecture</td><td className="p-3">Flight controller, sensors, GNSS/compass, receiver, telemetry, ESCs, motors and power paths</td></tr><tr><td className="p-3 font-semibold">Component matrix</td><td className="p-3">Ratings, interfaces, mass, compatibility evidence and source documentation</td></tr><tr><td className="p-3 font-semibold">Power budget</td><td className="p-3">Voltage, current capability, connector/wire ratings, expected load and reserve</td></tr><tr><td className="p-3 font-semibold">Mechanical layout</td><td className="p-3">Centre of mass, propeller clearance, vibration, cooling, antennas and strain relief</td></tr><tr><td className="p-3 font-semibold">Risk register</td><td className="p-3">Hazard, cause, consequence, control, verification and responsible person</td></tr></tbody></table></div><p className="mt-4 leading-8 text-slate-600">Complete a design review before purchasing or energising the build. Reject incompatible voltage, current, protocol, connector, firmware or mechanical combinations rather than relying on later software correction.</p></section>
 <section className="rounded-2xl bg-indigo-50 p-6"><div className="flex items-center gap-3"><Wrench className="text-indigo-700"/><h3 className="text-2xl font-bold">3. Build and configuration gates</h3></div><ol className="mt-5 space-y-3">{["Inspect and assemble the frame; verify motor screws, alignment, fasteners and propeller clearance.","Install components in documented orientation with cooling, isolation, antenna separation and service access.","Complete wiring, polarity, pinout, insulation, strain-relief and continuity inspections.","Perform current-limited first power-up and stop for unexpected current, heat, smell, sound or resets.","Install supported firmware and record board target, version, frame type and configuration baseline.","Calibrate sensors and receiver; verify displayed aircraft motion, channels, modes and arming logic.","With propellers removed, verify every motor number/direction and all detectable fail-safe actions.","Save a configuration backup and obtain checklist approval before any propeller installation."].map((x,i)=><li key={x} className="flex gap-4 rounded-xl bg-white p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-indigo-600 text-sm font-bold text-white">{i+1}</span>{x}</li>)}</ol></section>
 <section><div className="flex items-center gap-3"><TestTube2 className="text-amber-700"/><h3 className="text-2xl font-bold">4. Staged test programme</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Gate A — bench" text="Power, sensors, controls, motors, navigation, telemetry and fail-safe verification with propellers removed."/><Card title="Gate B — first hover" text="Brief low hover in a clear authorised area; evaluate control, vibration, sound, current and landing behaviour."/><Card title="Gate C — basic modes" text="Gentle, repeatable manoeuvres and only one new assisted function at a time with a known recovery mode."/><Card title="Gate D — GPS operation" text="Validate position hold and return behaviour only after navigation, home, boundary and altitude checks pass."/><Card title="Gate E — training mission" text="Run a short simulated-first waypoint mission with generous margins, observer and prepared pilot takeover."/><Card title="Gate F — repeatability" text="Repeat the accepted profile and compare logs to demonstrate stable performance rather than a single lucky result."/></div></section>
 <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h3 className="text-2xl font-bold">Acceptance evidence</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Photographs of build, wiring and antenna layout","Signed bench and pre-flight checklists","Firmware and versioned parameter backup","Mission/fence and contingency documents","Flight logs linked to each test card","Battery, vibration, navigation and link results","Defect and corrective-action records","Final requirement pass/fail matrix"].map(x=><li key={x} className="rounded-xl bg-white p-4">• {x}</li>)}</ul><p className="mt-4 leading-7 text-amber-900">Redact personal locations, identifiers and sensitive operating data before sharing reports publicly.</p></section>
 <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-red-700"/><h3 className="text-2xl font-bold">Critical safety rule</h3></div><p className="mt-4 leading-8 text-slate-700">Construction does not authorise flight. Follow current local aviation, radio, site, privacy and insurance requirements; use competent supervision and a suitable emergency plan. Never test above uninvolved people or beyond the approved operating area. A critical mechanical, electrical, control, navigation, communication, battery or documentation fault blocks the next gate until corrected and reverified.</p></section>
 <section className="rounded-2xl bg-slate-900 p-6 text-white"><div className="flex items-center gap-3"><FileCheck2/><h3 className="text-2xl font-bold">Final submission</h3></div><p className="mt-3 leading-7 text-slate-200">Submit a concise engineering report containing requirements, design rationale, diagrams, build record, risk register, acceptance checklists, configuration version, test cards, redacted logs, results, defects, corrective actions, final pass/fail matrix and honest limitations. Conclude with what you would change in the next design revision and why.</p></section>
 <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-950">Course capstone checklist</h3><p className="mt-3 leading-7 text-blue-900">Complete the reviewed design package, pass every build and test gate, preserve traceable evidence, resolve critical defects, present the final engineering report, and score at least 80% below. The course mock test and assessment remain separate from this chapter quiz.</p></section>
</article><ChapterQuiz/></>}

function ChapterQuiz(){const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;const reset=()=>{setAnswers({});setSubmitted(false)};return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b border-slate-200 pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 10 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border border-slate-200 p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=answers[i]===j;const correct=submitted&&j===q.answer;const incorrect=submitted&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":incorrect?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"border-slate-200 hover:bg-slate-50"}`}><input type="radio" name={`drone-ch10-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(a=>({...a,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!submitted?<button type="button" disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button type="button" onClick={reset} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}
function Card({title,text}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><h4 className="font-bold text-slate-900">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
