import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, CircleHelp, CloudCog, Fingerprint, KeyRound, LockKeyhole, RefreshCw, RotateCcw, ShieldCheck, Smartphone, UserRoundCheck, XCircle } from "lucide-react";

const questions = [
  { question: "What is the safest identity model for a fleet of IoT devices?", options: ["A unique identity and credential for every device", "One shared password for the whole fleet", "No authentication on a private network", "The serial number as a password"], answer: 0 },
  { question: "Why should device credentials be rotatable?", options: ["Compromised or expiring credentials can be replaced safely", "To increase sensor accuracy", "To remove encryption", "To make all devices administrators"], answer: 0 },
  { question: "What does least privilege mean?", options: ["Grant only the permissions required for the device or user task", "Grant full access by default", "Publish credentials in firmware", "Disable audit records"], answer: 0 },
  { question: "Which control best protects telemetry while travelling over a network?", options: ["TLS with certificate validation", "Base64 encoding", "A hidden topic name", "Short JSON keys"], answer: 0 },
  { question: "What is secure boot designed to do?", options: ["Run only trusted, verified firmware", "Boot without checking code", "Expose debug ports", "Disable updates"], answer: 0 },
  { question: "What should an OTA update process verify before installation?", options: ["Signature, integrity, compatibility and rollback safety", "Only the filename", "Only the Wi-Fi strength", "Nothing if the server is known"], answer: 0 },
  { question: "Why is data minimisation important?", options: ["It limits unnecessary privacy exposure and storage risk", "It makes every record public", "It replaces consent", "It prevents deletion"], answer: 0 },
  { question: "What is a good response to a lost or compromised device?", options: ["Revoke its identity, investigate events and rotate affected secrets", "Ignore it until it reconnects", "Give it broader access", "Delete all audit logs"], answer: 0 },
  { question: "Which practice improves fleet vulnerability management?", options: ["Maintain an inventory, software versions, update status and risk-based remediation", "Never record firmware versions", "Use unsupported libraries forever", "Keep default credentials"], answer: 0 },
  { question: "What should happen when a firmware update fails?", options: ["Recover to a known-good image and report the failure", "Remain permanently unbootable", "Accept unsigned firmware", "Erase device identity"], answer: 0 },
];

const threatRows = [
  ["Device", "Physical access, debug ports, extracted keys, malicious firmware", "Secure boot, protected storage, disabled production debug, tamper-aware design"],
  ["Network", "Eavesdropping, spoofing, replay, denial of service", "TLS, certificate validation, nonces/timestamps, rate limits and segmentation"],
  ["Cloud/API", "Broken access control, injection, leaked secrets, tenant crossover", "Strong authentication, scoped authorisation, validation, secret management and audit"],
  ["Application", "Weak sessions, unsafe sharing, excessive data exposure", "Secure sessions, role checks, privacy controls and minimal responses"],
  ["Supply chain", "Vulnerable dependency, compromised build or update package", "SBOM/inventory, pinned builds, signing, review and monitored release pipeline"],
];

export default function InternetOfThingsChapterEightLesson() {
  return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
    <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 8</p><h2 className="mt-2 text-3xl font-bold">IoT Security, Privacy and Device Management</h2><p className="mt-4 leading-8 text-slate-600">A connected device is a physical computer, a network client and a cloud identity. Security must therefore cover its entire lifecycle—from manufacture and onboarding to normal operation, updates, ownership transfer and retirement. This chapter develops a practical defence-in-depth model for trustworthy IoT fleets.</p></header>

    <section><h3 className="text-2xl font-bold">Learning objectives</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{["Model threats across device, network, cloud, application and supply-chain layers.", "Design unique device identities, secure onboarding and credential rotation.", "Apply encryption, least privilege, secure boot and protected secret storage.", "Plan signed OTA updates with staged rollout, health checks and rollback.", "Apply privacy-by-design through purpose limitation, consent, minimisation and retention.", "Operate a fleet using inventory, health, audit, incident and retirement controls."].map(x => <CheckItem key={x} text={x} />)}</div></section>

    <section className="rounded-2xl bg-slate-950 p-6 text-white"><div className="flex items-center gap-3"><ShieldCheck className="text-cyan-300"/><h3 className="text-2xl font-bold">Defence in depth</h3></div><p className="mt-3 leading-8 text-slate-300">No single control is sufficient. A secure product combines hardware trust, verified firmware, protected credentials, encrypted transport, authorised cloud APIs, monitored operations and a safe update path. If one control fails, the remaining layers limit damage.</p><div className="mt-5 overflow-x-auto rounded-2xl border border-white/15"><table className="w-full min-w-[800px] text-left"><thead className="bg-white/10"><tr><th className="p-4">Surface</th><th className="p-4">Typical threats</th><th className="p-4">Important controls</th></tr></thead><tbody className="divide-y divide-white/10">{threatRows.map(([a,b,c]) => <tr key={a}><th className="p-4 text-white">{a}</th><td className="p-4 text-slate-300">{b}</td><td className="p-4 text-slate-300">{c}</td></tr>)}</tbody></table></div></section>

    <section><Title icon={Fingerprint} text="Identity, onboarding and access"/><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Card title="Unique identity" text="Give each device a non-shared identity. Record model, owner, status and credential history in the registry."/><Card title="Secure onboarding" text="Use a short-lived claim or manufacturer identity, bind the device to the correct tenant, then issue operational credentials."/><Card title="Mutual trust" text="The device validates the server certificate; high-assurance systems also use mutual TLS so the server validates the device certificate."/><Card title="Least privilege" text="A sensor may publish only to its own telemetry topic and read only its permitted configuration—not another device or administrative API."/><Card title="Credential lifecycle" text="Generate secrets securely, store them in protected hardware where available, rotate before expiry and revoke immediately when compromised."/><Card title="Human access" text="Use role-based access, strong sign-in, short sessions and additional verification for sensitive administration or commands."/></div></section>

    <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><Title icon={LockKeyhole} text="Protecting data and commands" color="text-blue-700"/><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="In transit" text="Use current TLS, validate the complete certificate chain and hostname, reject weak fallback and protect against replay."/><Card title="At rest" text="Encrypt sensitive storage, separate encryption keys from data, restrict backups and test deletion across replicas and exports."/><Card title="Command safety" text="Authorise every command, validate parameters, require freshness and idempotency, log the decision and design a safe device response."/><Card title="Logging" text="Record identity, decision, time and result without logging passwords, private keys, full tokens or unnecessary personal data."/></div></section>

    <section><Title icon={Smartphone} text="Secure device and firmware"/><ol className="mt-5 space-y-3">{["Establish a hardware root of trust or protected boot key.", "Verify each boot-stage and firmware signature before execution.", "Lock or authenticate production debug interfaces and protect key storage.", "Use memory-safe boundaries, input validation and secure defaults in firmware.", "Enable watchdogs, fault reporting and a safe state for unsafe failures.", "Remove default passwords and unnecessary services before release."].map((x,i) => <Step key={x} number={i+1} text={x}/>)}</ol></section>

    <section className="rounded-2xl border border-violet-200 bg-violet-50 p-6"><Title icon={RefreshCw} text="Safe over-the-air updates" color="text-violet-700"/><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Card title="1. Prepare" text="Build reproducibly, scan dependencies, version the package and sign the approved manifest and image."/><Card title="2. Authorise" text="Device verifies signer, integrity, model compatibility, version policy and available power/storage."/><Card title="3. Stage" text="Release first to internal and small canary groups; monitor boot, connectivity, crash and functional health."/><Card title="4. Recover" text="Use an A/B image or known-good recovery path. Never mark the new image healthy before successful validation."/><Card title="5. Expand" text="Increase rollout gradually, pause automatically on abnormal failure rates and retain campaign audit evidence."/><Card title="6. Maintain" text="Publish support periods, patch critical issues promptly and securely retire products that can no longer be supported."/></div><div className="mt-5 flex gap-3 rounded-xl bg-white p-4 text-violet-950"><AlertTriangle className="mt-0.5 shrink-0 text-amber-600"/><p><b>Anti-rollback requires care:</b> blocking older vulnerable firmware is useful, but the device must still retain a tested signed recovery image and a controlled emergency process.</p></div></section>

    <section><Title icon={UserRoundCheck} text="Privacy by design"/><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="Purpose and transparency" text="State what is collected, why it is required, who receives it and how long it is kept in language users understand."/><Card title="Data minimisation" text="Collect the least detail and frequency required. Prefer local processing when the cloud does not need raw personal data."/><Card title="Choice and control" text="Implement applicable consent, access, correction, export and deletion workflows rather than relying on a privacy notice alone."/><Card title="Retention and transfer" text="Apply deletion to raw data, aggregates, backups and vendor copies; define a safe ownership-transfer and factory-reset process."/></div></section>

    <section className="rounded-2xl bg-cyan-50 p-6"><Title icon={CloudCog} text="Fleet management lifecycle" color="text-cyan-800"/><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Lifecycle title="Provision" text="Register identity, ownership, model, approved firmware and initial policy."/><Lifecycle title="Monitor" text="Track connectivity, software version, configuration drift, security events and health."/><Lifecycle title="Maintain" text="Rotate credentials, patch vulnerabilities, stage updates and preserve audit history."/><Lifecycle title="Retire" text="Revoke identity, erase protected data, remove ownership and document disposal or transfer."/></div></section>

    <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><Title icon={AlertTriangle} text="Incident response" color="text-red-700"/><ol className="mt-5 grid gap-3 md:grid-cols-2">{["Detect abnormal authentication, traffic, configuration or firmware behaviour.", "Contain by revoking credentials, quarantining devices or pausing an update campaign.", "Preserve relevant logs, versions and timelines without exposing secrets.", "Eradicate the cause, rotate affected credentials and deploy a verified repair.", "Recover gradually and confirm device, service and safety health.", "Notify affected parties when required and improve controls after the review."].map((x,i) => <Step key={x} number={i+1} text={x}/>)}</ol></section>

    <section className="rounded-2xl bg-indigo-50 p-6"><h3 className="text-2xl font-bold text-indigo-950">Hands-on project: secure fleet plan</h3><p className="mt-3 leading-8 text-indigo-900">Design security and device management for ten ESP32 environmental nodes installed at two sites.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{["Draw trust boundaries and list assets, actors, entry points and threats.", "Define per-device identity, topic/API permissions and onboarding steps.", "Specify secure boot, protected secrets and production debug policy.", "Create a signed A/B OTA rollout with canary, health check and rollback.", "Define telemetry purpose, personal-data fields, retention and deletion.", "Write lost-device and compromised-key incident playbooks."].map(x => <CheckItem key={x} text={x}/>)}</div></section>

    <section><h3 className="text-2xl font-bold">Troubleshooting and verification</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><Card title="TLS connection fails" text="Check device time, certificate chain, hostname, trust store, expiry and supported protocol before weakening validation."/><Card title="Device rejected after rotation" text="Confirm activation overlap, correct device binding and clock validity; never restore a revoked shared secret as a shortcut."/><Card title="OTA device boot loop" text="Inspect update and boot-health logs, return to the signed known-good slot, then reproduce safely before retrying rollout."/><Card title="Unexpected cross-device data" text="Stop exposure, examine tenant/device filters and authorisation, preserve evidence, rotate affected credentials and test isolation."/></div></section>

    <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h3 className="text-xl font-bold text-emerald-950">Chapter completion checklist</h3><div className="mt-4 grid gap-2 md:grid-cols-2">{["Threat model covers every system layer.", "Each device has a revocable identity.", "Transport and stored data are protected.", "Firmware boot and OTA packages are verified.", "Privacy purpose and retention are documented.", "Fleet monitoring and incident playbooks are testable."].map(x => <CheckItem key={x} text={x}/>)}</div><p className="mt-5 text-emerald-900">Complete the secure fleet plan and score at least 80% in the chapter quiz.</p></section>
  </article><ChapterQuiz/></>;
}

function ChapterQuiz(){const [answers,setAnswers]=useState({});const [submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 8 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((option,j)=>{const selected=answers[i]===j,correct=submitted&&j===q.answer,wrong=submitted&&selected&&j!==q.answer;return <label key={option} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":wrong?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"hover:bg-slate-50"}`}><input type="radio" name={`iot-ch8-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(v=>({...v,[i]:j}))} className="mt-1"/><span>{option}</span></label>})}</div></fieldset>)}</div>{!submitted?<button disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button onClick={()=>{setAnswers({});setSubmitted(false)}} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}
function Title({icon:Icon,text,color="text-indigo-700"}){return <div className="flex items-center gap-3"><Icon className={color}/><h3 className="text-2xl font-bold">{text}</h3></div>}
function Card({title,text}){return <div className="rounded-2xl border bg-white p-5"><h4 className="font-bold">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
function CheckItem({text}){return <div className="flex gap-3 rounded-xl border bg-white p-4"><CheckCircle2 className="mt-0.5 shrink-0 text-emerald-600" size={20}/><span>{text}</span></div>}
function Step({number,text}){return <li className="flex gap-4 rounded-xl border bg-white p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-700 text-sm font-bold text-white">{number}</span><span>{text}</span></li>}
function Lifecycle({title,text}){return <div className="rounded-2xl bg-white p-5"><h4 className="font-bold text-cyan-950">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
