import { useMemo, useState } from "react";
import { Activity, AlertTriangle, CheckCircle2, CircleHelp, Filter, Gauge, Lightbulb, RotateCcw, ShieldCheck, SlidersHorizontal, Timer, XCircle, Zap } from "lucide-react";

const questions = [
  { question: "What does a sensor do?", options: ["Converts a physical condition into usable data", "Always drives a motor directly", "Stores every cloud record", "Creates a Wi-Fi password"], answer: 0 },
  { question: "What is an actuator?", options: ["A device that converts a command into a physical action", "Only a temperature sensor", "A cloud database", "A serial monitor"], answer: 0 },
  { question: "Why must a 5 V analogue output not be connected directly to an ESP32 ADC pin?", options: ["It may exceed the ESP32 input rating", "It improves accuracy too much", "It disables USB", "It changes the IDE language"], answer: 0 },
  { question: "What is calibration?", options: ["Comparing and adjusting measurements against a known reference", "Increasing every reading by ten", "Removing timestamps", "Connecting a relay without a driver"], answer: 0 },
  { question: "Which measure best describes the smallest detectable input change?", options: ["Resolution", "Range", "Latency", "Enclosure size"], answer: 0 },
  { question: "Why is a transistor or driver used with a relay or motor?", options: ["GPIO cannot safely supply the required load current", "It makes the sensor digital", "It stores data", "It replaces the power supply"], answer: 0 },
  { question: "What is the purpose of a flyback diode across a DC inductive load?", options: ["Limit the voltage spike when current is switched off", "Increase Wi-Fi range", "Measure humidity", "Create PWM"], answer: 0 },
  { question: "What does a moving-average filter do?", options: ["Smooths short-term measurement noise using recent samples", "Guarantees a correct sensor", "Encrypts data", "Changes a digital pin into a power output"], answer: 0 },
  { question: "Why should IoT telemetry include units and timestamps?", options: ["So measurements can be interpreted and ordered correctly", "Only to increase message size", "To hide sensor identity", "To remove validation"], answer: 0 },
  { question: "What is the best response to an invalid sensor reading?", options: ["Validate it, mark its quality and apply a defined safe policy", "Always operate the actuator at maximum", "Publish it as trusted data", "Disable all diagnostics"], answer: 0 },
];

const samplingCode = `const int SENSOR_PIN = 34;
const unsigned long SAMPLE_MS = 1000;
unsigned long lastSample = 0;

void setup() {
  Serial.begin(115200);
  analogReadResolution(12);
}

void loop() {
  unsigned long now = millis();
  if (now - lastSample >= SAMPLE_MS) {
    lastSample = now;
    int raw = analogRead(SENSOR_PIN);
    Serial.printf("raw=%d,time_ms=%lu\\n", raw, now);
  }
}`;

const filteringCode = `const int WINDOW = 8;
int samples[WINDOW] = {0};
int position = 0;
long total = 0;

float updateAverage(int newSample) {
  total -= samples[position];
  samples[position] = newSample;
  total += newSample;
  position = (position + 1) % WINDOW;
  return total / float(WINDOW);
}`;

export default function InternetOfThingsChapterFourLesson() {
  return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
    <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 4</p><h2 className="mt-2 text-3xl font-bold">Sensors, Actuators and Edge Data Acquisition</h2><p className="mt-4 leading-8 text-slate-600">An IoT system is only as trustworthy as the physical data it collects and the actions it performs. This chapter explains how to select, connect, sample, validate, calibrate and filter sensors on an ESP32, and how to control actuators through safe driver circuits. The goal is dependable edge data—not merely a number printed by a library.</p></header>

    <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Classify analogue, digital, resistive, pulse and bus-connected sensors.", "Interpret range, accuracy, precision, resolution, sensitivity and response time.", "Protect ESP32 inputs and safely interface sensors with different voltage levels.", "Design timed, non-blocking acquisition with validation and data-quality indicators.", "Apply calibration, averaging, deadband and threshold techniques appropriately.", "Control LEDs, relays, motors and other actuators through suitable drivers and fail-safe logic."].map((item)=><li key={item} className="rounded-xl border p-4"><b className="mr-2 text-emerald-600">✓</b>{item}</li>)}</ul></section>

    <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><Activity className="text-blue-700"/><h3 className="text-2xl font-bold text-blue-950">From physical quantity to useful data</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Flow title="1. Transduction" text="A sensing element reacts to temperature, light, pressure, motion or another quantity."/><Flow title="2. Conditioning" text="The signal may be amplified, filtered, divided, isolated or converted."/><Flow title="3. Conversion" text="An ADC, counter or digital interface produces a value for firmware."/><Flow title="4. Interpretation" text="Firmware validates, calibrates, timestamps and gives the value meaning."/></div></section>

    <section><div className="flex items-center gap-3"><Gauge className="text-indigo-700"/><h3 className="text-2xl font-bold">Sensor interface types</h3></div><div className="mt-5 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-4">Interface</th><th className="p-4">Information form</th><th className="p-4">Example</th><th className="p-4">Design concern</th></tr></thead><tbody className="divide-y"><SensorRow type="Analogue voltage" form="Continuous voltage converted by ADC" example="Light or soil-moisture module" concern="Voltage range, noise and ADC calibration"/><SensorRow type="Digital state" form="HIGH/LOW logic level" example="Door switch or motion output" concern="Pull resistor, debouncing and voltage compatibility"/><SensorRow type="Pulse/frequency" form="Timing, count or duty cycle" example="Flow sensor or speed encoder" concern="Interrupt rate, pulse width and missed edges"/><SensorRow type="I2C/SPI/UART" form="Structured digital registers or frames" example="Environmental sensor or GNSS module" concern="Addressing, wiring, bus speed and error handling"/></tbody></table></div></section>

    <section className="rounded-2xl border border-cyan-200 bg-cyan-50 p-6"><div className="flex items-center gap-3"><SlidersHorizontal className="text-cyan-700"/><h3 className="text-2xl font-bold text-cyan-950">Measurement vocabulary</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Term name="Range" text="Minimum to maximum quantity the sensor is designed to measure."/><Term name="Accuracy" text="Closeness of a result to the accepted reference value."/><Term name="Precision" text="Repeatability of measurements under the same conditions."/><Term name="Resolution" text="Smallest input change represented by the measurement system."/><Term name="Sensitivity" text="Change in output produced by a change in the measured quantity."/><Term name="Response time" text="Time required to follow a change within a stated tolerance."/></div><p className="mt-5 rounded-xl bg-white p-4 leading-7 text-slate-700">More ADC bits do not automatically create an accurate instrument. Reference stability, sensor error, noise, grounding, calibration and environmental effects still determine useful performance.</p></section>

    <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><AlertTriangle className="text-red-700"/><h3 className="text-2xl font-bold text-red-950">Safe sensor interfacing</h3></div><ul className="mt-4 space-y-2 leading-7 text-red-900"><li>• Confirm sensor supply voltage and output voltage separately; a 5 V-powered module may output 5 V.</li><li>• Keep ESP32 GPIO and ADC signals within documented limits; use a divider, buffer or level shifter where required.</li><li>• Use a common ground for non-isolated circuits and keep analogue return paths away from noisy motor currents.</li><li>• Add current limiting, ESD protection, filtering or isolation according to the environment and connector exposure.</li><li>• Never connect mains voltage or an unknown industrial signal directly to the development board.</li></ul></section>

    <section><div className="flex items-center gap-3"><Timer className="text-blue-700"/><h3 className="text-2xl font-bold">Sampling and timing</h3></div><p className="mt-3 leading-8 text-slate-600">Sample fast enough to capture meaningful change, but not so fast that power, bandwidth and storage are wasted. Separate sampling rate from publication rate: a device can sample every second, calculate a one-minute summary and publish only the summary plus important events.</p><CodeBlock code={samplingCode}/><div className="mt-5 grid gap-4 md:grid-cols-2"><Info title="Blocking delay" text="Simple for demonstrations but prevents other work during the wait and becomes unsuitable as networking and control grow."/><Info title="millis()-based scheduling" text="Checks elapsed time without stopping the processor, allowing sensing, connectivity and actuator state machines to progress together."/></div></section>

    <section className="rounded-2xl bg-slate-900 p-6 text-white"><div className="flex items-center gap-3"><Filter className="text-cyan-300"/><h3 className="text-2xl font-bold">Validation, calibration and filtering</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Dark title="Validation" text="Reject impossible values, detect stale timestamps, check communication status and assign a data-quality state."/><Dark title="Calibration" text="Compare against traceable or suitable references, calculate correction and record conditions and date."/><Dark title="Filtering" text="Reduce unwanted variation using methods justified by signal behaviour; do not hide genuine rapid change."/><Dark title="Hysteresis/deadband" text="Use separate on and off thresholds to prevent an actuator rapidly switching around one boundary."/></div><CodeBlock code={filteringCode}/></section>

    <section><h3 className="text-2xl font-bold">A practical data-quality model</h3><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Quality state="GOOD" colour="bg-emerald-100 text-emerald-800" text="Validated, fresh and within the expected operating range."/><Quality state="UNCERTAIN" colour="bg-amber-100 text-amber-800" text="Usable with caution—for example during warm-up or marginal signal."/><Quality state="STALE" colour="bg-blue-100 text-blue-800" text="Last valid result is older than the permitted age."/><Quality state="BAD" colour="bg-red-100 text-red-800" text="Invalid, failed or unavailable; do not use for unsafe control."/></div><p className="mt-5 leading-7 text-slate-600">Publish value, unit, timestamp and quality together. A last-known value without age or quality can mislead a dashboard and automation rule.</p></section>

    <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-center gap-3"><Zap className="text-amber-700"/><h3 className="text-2xl font-bold text-amber-950">Safe actuator control</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Actuator title="Indicator LED" driver="Series current-limiting resistor" safety="Use GPIO current limits and initialise to a known state."/><Actuator title="Relay" driver="Transistor/MOSFET, flyback diode and suitable supply" safety="Choose a safe de-energised state; isolate hazardous loads."/><Actuator title="DC motor or pump" driver="Motor driver or rated MOSFET stage" safety="Handle stall current, electrical noise and emergency stop."/><Actuator title="Servo" driver="Control pulse plus adequately rated external power" safety="Share ground, limit travel and avoid regulator overload."/></div><p className="mt-5 rounded-xl bg-white p-4 leading-7 text-slate-700"><b>Boot safety:</b> configure actuator pins and safe initial outputs before enabling drivers. Never allow a reset, disconnected sensor or malformed cloud command to activate hazardous equipment.</p></section>

    <section><h3 className="text-2xl font-bold">Edge acquisition pipeline</h3><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Pipeline number="1" title="Acquire" text="Read the interface and capture a monotonic or real timestamp."/><Pipeline number="2" title="Validate" text="Check communication, range, freshness and sensor status."/><Pipeline number="3" title="Convert" text="Apply engineering units and documented calibration."/><Pipeline number="4" title="Filter" text="Smooth noise or detect events without masking faults."/><Pipeline number="5" title="Decide" text="Apply thresholds, hysteresis and local safety rules."/><Pipeline number="6" title="Package" text="Publish value, unit, time, identity and quality metadata."/></div></section>

    <section className="rounded-2xl bg-indigo-50 p-6"><div className="flex items-center gap-3"><Lightbulb className="text-indigo-700"/><h3 className="text-2xl font-bold text-indigo-950">Hands-on project: environmental edge node</h3></div><p className="mt-3 leading-8 text-indigo-900">Connect a compatible temperature/humidity sensor and an LED or low-voltage relay driver to the ESP32. Sample periodically, validate data, calculate a filtered temperature, apply hysteresis to the output and print a structured telemetry record.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{["Draw the circuit with supply voltage, common ground and GPIO labels.", "Record sensor range, accuracy, interface and warm-up requirements.", "Select sampling and reporting intervals with justification.", "Include value, unit, timestamp, quality and output state in telemetry.", "Test normal, threshold, disconnected-sensor and reset conditions.", "Document measured references, correction and remaining uncertainty."].map((item)=><div key={item} className="flex gap-3 rounded-xl bg-white p-4"><CheckCircle2 className="mt-0.5 shrink-0 text-indigo-600" size={20}/><span>{item}</span></div>)}</div></section>

    <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-emerald-700"/><h3 className="text-xl font-bold text-emerald-950">Verification checklist</h3></div><ul className="mt-4 space-y-2 leading-7 text-emerald-900"><li>• Voltage, current, polarity and pin capabilities verified before power-up.</li><li>• Raw and engineering-unit readings observable for diagnosis.</li><li>• Invalid, stale and disconnected sensor conditions handled explicitly.</li><li>• Output driver rated for the load and default state confirmed safe.</li><li>• Threshold and hysteresis tested on both rising and falling input.</li><li>• Telemetry carries identity, unit, timestamp and quality.</li></ul></section>

    <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-950">Chapter revision summary</h3><ul className="mt-4 space-y-2 leading-7 text-blue-900"><li>• Reliable acquisition begins with correct electrical interfacing and documented sensor characteristics.</li><li>• Sampling, validation, calibration, filtering and interpretation are separate steps.</li><li>• More resolution does not guarantee greater accuracy.</li><li>• Actuators require drivers, protection, sufficient power and fail-safe defaults.</li><li>• Useful telemetry includes context and data quality, not only a numeric value.</li></ul></section>

    <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h3 className="text-xl font-bold text-emerald-950">Chapter completion checklist</h3><p className="mt-3 leading-7 text-emerald-900">Complete the environmental-node activity, explain measurement terminology, implement non-blocking sampling and hysteresis, demonstrate safe fault behaviour, produce structured telemetry and score at least 80% in the quiz.</p></section>
  </article><ChapterQuiz/></>;
}

function ChapterQuiz(){const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((t,q,i)=>t+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;const reset=()=>{setAnswers({});setSubmitted(false);};return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 4 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=answers[i]===j;const correct=submitted&&j===q.answer;const incorrect=submitted&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":incorrect?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"hover:bg-slate-50"}`}><input type="radio" name={`iot-ch4-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(c=>({...c,[i]:j}))} className="mt-1"/><span>{o}</span></label>;})}</div></fieldset>)}</div>{!submitted?<button disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button onClick={reset} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>;}

function Flow({title,text}){return <div className="rounded-2xl bg-white p-5"><h4 className="font-bold text-blue-900">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>;}
function SensorRow({type,form,example,concern}){return <tr><th className="p-4 font-bold">{type}</th><td className="p-4">{form}</td><td className="p-4">{example}</td><td className="p-4">{concern}</td></tr>;}
function Term({name,text}){return <div className="rounded-2xl bg-white p-5"><h4 className="font-bold text-cyan-900">{name}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>;}
function Info({title,text}){return <div className="rounded-2xl border p-5"><h4 className="font-bold">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>;}
function CodeBlock({code}){return <pre className="mt-5 overflow-x-auto rounded-2xl bg-black/40 p-5 text-sm leading-7 text-cyan-100"><code>{code}</code></pre>;}
function Dark({title,text}){return <div className="rounded-2xl border border-white/15 bg-white/10 p-5"><h4 className="font-bold text-cyan-200">{title}</h4><p className="mt-2 leading-7 text-slate-200">{text}</p></div>;}
function Quality({state,colour,text}){return <div className="rounded-2xl border p-5"><span className={`rounded-full px-3 py-1 text-sm font-bold ${colour}`}>{state}</span><p className="mt-3 leading-7 text-slate-600">{text}</p></div>;}
function Actuator({title,driver,safety}){return <div className="rounded-2xl bg-white p-5"><h4 className="font-bold text-amber-950">{title}</h4><p className="mt-2 text-slate-700"><b>Driver:</b> {driver}</p><p className="mt-2 text-slate-700"><b>Safety:</b> {safety}</p></div>;}
function Pipeline({number,title,text}){return <div className="rounded-2xl border p-5"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-blue-600 font-bold text-white">{number}</span><h4 className="mt-3 font-bold">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>;}
