import { useMemo, useState } from "react";
import { AlertTriangle, BarChart3, BellRing, CheckCircle2, CircleHelp, Cloud, Database, Gauge, KeyRound, Layers3, Lightbulb, LockKeyhole, RotateCcw, ServerCog, ShieldCheck, Timer, Users, XCircle } from "lucide-react";

const questions=[
 {question:"What should an IoT ingestion service do before accepting telemetry?",options:["Authenticate the device and validate the message contract","Trust every payload","Remove timestamps","Give every user administrator access"],answer:0},
 {question:"Why is time-series storage useful for telemetry?",options:["It organises measurements by time for trends and aggregation","It powers sensors","It replaces device identity","It disables retention"],answer:0},
 {question:"What is the purpose of a device registry?",options:["Maintain device identity, metadata, ownership and lifecycle state","Store only dashboard colours","Replace all databases","Publish public passwords"],answer:0},
 {question:"What is downsampling?",options:["Producing lower-resolution summaries from detailed historical data","Deleting every record immediately","Increasing sensor voltage","Sending commands without validation"],answer:0},
 {question:"Which dashboard design is most useful?",options:["Shows current state, time context, units, quality and actionable exceptions","Uses gauges for every value","Hides stale data","Shows no timestamps"],answer:0},
 {question:"What prevents an alert from repeatedly switching near one threshold?",options:["Hysteresis and an alert state machine","A larger font","Removing timestamps","Anonymous access"],answer:0},
 {question:"Why should telemetry and configuration permissions be separated?",options:["They carry different risk and require least privilege","They must always be public","It makes data unstructured","It removes authentication"],answer:0},
 {question:"What is a retention policy?",options:["A rule defining how long data is kept and when it is aggregated or deleted","A Wi-Fi retry timer","A GPIO mode","An MQTT client ID"],answer:0},
 {question:"What should a platform do with duplicate event submissions?",options:["Use an event identifier or idempotent processing to avoid duplicate effects","Send duplicate alerts forever","Disable validation","Execute every command twice"],answer:0},
 {question:"Which metric helps control cloud operating cost?",options:["Messages, stored bytes, queries, egress and rule executions","PCB colour","LED size","USB cable length only"],answer:0},
];

const telemetrySchema=`{
  "eventId": "01J-IOT-000184",
  "schemaVersion": 1,
  "deviceId": "room-node-07",
  "capturedAt": "2026-09-14T13:15:00Z",
  "receivedAt": "2026-09-14T13:15:01Z",
  "measurements": {
    "temperatureC": 28.4,
    "humidityPercent": 67
  },
  "quality": "GOOD"
}`;

const queryExample=`SELECT
  device_id,
  DATE_TRUNC('hour', captured_at) AS hour,
  AVG(temperature_c) AS average_temperature_c,
  MIN(temperature_c) AS minimum_temperature_c,
  MAX(temperature_c) AS maximum_temperature_c
FROM telemetry
WHERE captured_at >= :start_time
  AND captured_at < :end_time
GROUP BY device_id, DATE_TRUNC('hour', captured_at);`;

export default function InternetOfThingsChapterSevenLesson(){return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
 <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 7</p><h2 className="mt-2 text-3xl font-bold">Cloud Platforms, Databases and IoT Dashboards</h2><p className="mt-4 leading-8 text-slate-600">An IoT cloud platform turns device messages into trusted records, operational insight, alerts and controlled actions. This chapter follows telemetry from secure ingestion through validation, storage, aggregation, rules and dashboards, while keeping device ownership, privacy, retention, reliability and cost visible throughout the design.</p></header>
 <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Explain device registry, ingestion, processing, storage, rules, API and dashboard functions.","Design a versioned telemetry record with event, device and time identity.","Compare relational, document, key-value and time-series storage use cases.","Create useful dashboard views with units, freshness and data-quality context.","Design alerts with thresholds, hysteresis, duration, deduplication and recovery.","Define access, retention, audit, availability and cost controls for an IoT platform."].map(x=><li key={x} className="rounded-xl border p-4"><b className="mr-2 text-emerald-600">✓</b>{x}</li>)}</ul></section>

 <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><Cloud className="text-blue-700"/><h3 className="text-2xl font-bold text-blue-950">Device-to-dashboard data path</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-5"><Flow title="1. Ingest" text="Authenticate endpoint, authorise topic/API and bound the message."/><Flow title="2. Validate" text="Check schema, identity, timestamp, units, range and quality."/><Flow title="3. Process" text="Normalise, enrich, deduplicate, aggregate and apply rules."/><Flow title="4. Store" text="Write current state and history to suitable data stores."/><Flow title="5. Present" text="Serve dashboards, alerts, reports and controlled APIs."/></div></section>

 <section><div className="flex items-center gap-3"><Layers3 className="text-indigo-700"/><h3 className="text-2xl font-bold">Core platform services</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Service icon={KeyRound} title="Device registry" text="Stores stable identity, model, ownership, credential status, firmware, tags and lifecycle state."/><Service icon={ServerCog} title="Message ingestion" text="Terminates MQTT or HTTP connections, authenticates clients, applies limits and routes accepted messages."/><Service icon={Database} title="Data services" text="Maintain latest state, historical telemetry, configuration, audit records and derived aggregates."/><Service icon={Gauge} title="Rules and analytics" text="Evaluate thresholds, trends, schedules and domain logic to create events and actions."/><Service icon={BellRing} title="Notifications" text="Deliver deduplicated alerts through approved channels with escalation and acknowledgement."/><Service icon={Users} title="Application access" text="Authorised dashboards and APIs expose only the sites, devices and operations permitted to each user."/></div></section>

 <section className="rounded-2xl border border-cyan-200 bg-cyan-50 p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-cyan-700"/><h3 className="text-2xl font-bold text-cyan-950">Secure ingestion pipeline</h3></div><ol className="mt-5 space-y-3">{["Authenticate the device connection and verify credential status.","Authorise the exact publish topic or API resource.","Reject unsupported content types and oversized payloads early.","Parse with resource limits; validate schema version, required fields and types.","Verify device identity, timestamp reasonableness, ranges, units and quality.","Use event IDs or idempotent writes to handle retransmission safely.","Record an auditable acceptance or safe rejection without logging secrets."].map((x,i)=><li key={x} className="flex gap-4 rounded-xl bg-white p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-cyan-700 text-sm font-bold text-white">{i+1}</span><span>{x}</span></li>)}</ol></section>

 <section><div className="flex items-center gap-3"><Database className="text-blue-700"/><h3 className="text-2xl font-bold">Telemetry record design</h3></div><pre className="mt-5 overflow-x-auto rounded-2xl bg-slate-950 p-5 text-sm leading-7 text-cyan-100"><code>{telemetrySchema}</code></pre><div className="mt-5 grid gap-4 md:grid-cols-2"><Info title="Captured time" text="When the device measured the condition. Needed for correct historical order, including delayed uploads."/><Info title="Received time" text="When the platform accepted the message. Useful for diagnosing latency, clock error and backlog."/><Info title="Event identity" text="A unique event ID supports deduplication and audit when clients retry QoS or HTTP submissions."/><Info title="Schema version" text="Lets services interpret old and new payloads predictably while a fleet is upgraded gradually."/></div></section>

 <section className="rounded-2xl bg-slate-900 p-6 text-white"><h3 className="text-2xl font-bold">Choosing data storage</h3><div className="mt-5 overflow-x-auto rounded-2xl border border-white/15"><table className="w-full min-w-[780px] text-left"><thead className="bg-white/10"><tr><th className="p-4">Store</th><th className="p-4">Good fit</th><th className="p-4">Example</th><th className="p-4">Watch for</th></tr></thead><tbody className="divide-y divide-white/10 text-slate-200"><StoreRow name="Time-series" fit="Measurements ordered by time" example="Temperature history and aggregates" watch="Retention, cardinality and query windows"/><StoreRow name="Relational" fit="Structured relationships and transactions" example="Users, sites, devices and enrollment" watch="Schema evolution and write volume"/><StoreRow name="Document" fit="Flexible object-shaped records" example="Device configuration by model" watch="Validation and duplicated fields"/><StoreRow name="Key-value" fit="Fast lookup by a known key" example="Latest device state or access cache" watch="Limited ad-hoc query patterns"/><StoreRow name="Object storage" fit="Large immutable files" example="Images, logs, exports and firmware" watch="Metadata indexing and lifecycle rules"/></tbody></table></div></section>

 <section><h3 className="text-2xl font-bold">Raw data, aggregates and retention</h3><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Retention title="Raw window" text="Keep detailed samples only as long as troubleshooting, compliance and product requirements justify."/><Retention title="Downsample" text="Create minute, hourly or daily summaries for long-term trend analysis at lower cost."/><Retention title="Archive" text="Move approved historical data to lower-cost storage when infrequent access is acceptable."/><Retention title="Delete" text="Remove expired data and derived copies according to documented privacy and retention policy."/></div><CodeBlock code={queryExample}/></section>

 <section className="rounded-2xl border border-violet-200 bg-violet-50 p-6"><div className="flex items-center gap-3"><BarChart3 className="text-violet-700"/><h3 className="text-2xl font-bold text-violet-950">Designing an operational dashboard</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Dashboard title="Fleet summary" text="Online, offline, stale, alarmed and maintenance-due device counts with clear definitions."/><Dashboard title="Current state" text="Latest value, unit, quality, captured time and age—not a value without freshness context."/><Dashboard title="Historical trend" text="Time range, timezone, gaps, thresholds and related events displayed without misleading interpolation."/><Dashboard title="Exceptions first" text="Prioritise actionable alarms, affected assets, duration, acknowledgement and owner."/><Dashboard title="Drill-down" text="Move from fleet to site to device to raw evidence while preserving filters and time range."/><Dashboard title="Accessible presentation" text="Use text, icons and contrast in addition to colour; label axes and make layouts responsive."/></div><p className="mt-5 rounded-xl bg-white p-4 leading-7 text-slate-700">A gauge is useful only when the present value and limits matter. A trend chart is better for change over time; a table is better for exact comparison; a status list is better for operational exceptions.</p></section>

 <section><div className="flex items-center gap-3"><BellRing className="text-red-700"/><h3 className="text-2xl font-bold">Alert lifecycle</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><AlertStep number="1" title="Detect" text="Threshold, duration, rate of change, absence or device-reported fault becomes true."/><AlertStep number="2" title="Open" text="Create one alert identity with severity, evidence and affected asset."/><AlertStep number="3" title="Notify" text="Route by severity, schedule and ownership; retry delivery without duplicate incidents."/><AlertStep number="4" title="Acknowledge" text="Record who accepted responsibility and when."/><AlertStep number="5" title="Resolve" text="Confirm recovery conditions for a defined period, using hysteresis where needed."/><AlertStep number="6" title="Review" text="Measure response, false alarms and recurrence; improve the rule and operating process."/></div></section>

 <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-center gap-3"><Timer className="text-amber-700"/><h3 className="text-2xl font-bold text-amber-950">Avoid alert storms</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Info title="Hysteresis and duration" text="Require the condition to persist and use separate opening and recovery thresholds."/><Info title="Deduplication" text="Update an existing incident rather than opening a new alert for every sample."/><Info title="Suppression" text="Suppress dependent symptoms when a known parent failure, maintenance window or outage is active."/><Info title="Escalation" text="Notify the next responsible role only if severity or acknowledgement rules require it."/></div></section>

 <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><LockKeyhole className="text-red-700"/><h3 className="text-2xl font-bold text-red-950">Cloud security and privacy</h3></div><div className="mt-5 grid gap-3 md:grid-cols-2">{["Separate device identities from human users and service accounts.","Enforce tenant, site and device-level authorisation on every API query.","Encrypt data in transit and protect sensitive stored data with managed access.","Keep credentials out of telemetry, dashboards, exports and diagnostic logs.","Record administrative changes, command requests and access decisions in audit logs.","Minimise personal data and enforce retention, deletion and ownership-transfer procedures."].map(x=><div key={x} className="flex gap-3 rounded-xl bg-white p-4"><CheckCircle2 className="mt-0.5 shrink-0 text-red-600" size={20}/><span>{x}</span></div>)}</div></section>

 <section><h3 className="text-2xl font-bold">Reliability and cost controls</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><Info title="Backpressure and quotas" text="Protect ingestion and downstream services with per-device limits, bounded queues and controlled rejection."/><Info title="Dead-letter handling" text="Quarantine messages that cannot be processed, with safe metadata and a reviewed replay procedure."/><Info title="Observability" text="Track accepted/rejected messages, processing delay, storage errors, query latency, alert delivery and cost."/><Info title="Cost model" text="Estimate message count, rule executions, stored bytes, queries, data egress, notifications and retention before fleet rollout."/></div></section>

 <section className="rounded-2xl bg-indigo-50 p-6"><div className="flex items-center gap-3"><Lightbulb className="text-indigo-700"/><h3 className="text-2xl font-bold text-indigo-950">Hands-on project: environmental monitoring dashboard</h3></div><p className="mt-3 leading-8 text-indigo-900">Build the service design for five environmental nodes. Ingest versioned telemetry, maintain current device state, chart history and generate a temperature alert only after a sustained condition.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{["Define registry metadata, ownership and device lifecycle states.","Validate and deduplicate telemetry using eventId and schemaVersion.","Store latest state separately from historical measurements.","Create current-state, fleet-health and 24-hour trend views.","Open an alert after five high samples and resolve below a lower threshold.","Document user roles, retention periods, audit events and monthly cost drivers."].map(x=><div key={x} className="flex gap-3 rounded-xl bg-white p-4"><CheckCircle2 className="mt-0.5 shrink-0 text-indigo-600" size={20}/><span>{x}</span></div>)}</div></section>

 <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-emerald-700"/><h3 className="text-xl font-bold text-emerald-950">Verification checklist</h3></div><ul className="mt-4 space-y-2 leading-7 text-emerald-900"><li>• Unauthorised, malformed, oversized and duplicate messages are safely rejected.</li><li>• Device and captured times are retained alongside platform received time.</li><li>• Dashboard values show units, quality and freshness.</li><li>• Alerts deduplicate, escalate, acknowledge and resolve predictably.</li><li>• Retention and deletion apply to raw, aggregate, export and backup data as required.</li><li>• Platform health, security events and cost drivers are measurable.</li></ul></section>
 <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-950">Chapter revision summary</h3><ul className="mt-4 space-y-2 leading-7 text-blue-900"><li>• Cloud platforms authenticate, ingest, validate, process, store and present device information.</li><li>• Current state, time-series history, configuration and large files need different storage patterns.</li><li>• Dashboards must expose freshness, units, quality and actionable exceptions.</li><li>• Alerting requires state, duration, hysteresis, deduplication, ownership and recovery.</li><li>• Access control, retention, observability and cost are architecture requirements.</li></ul></section>
 <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h3 className="text-xl font-bold text-emerald-950">Chapter completion checklist</h3><p className="mt-3 leading-7 text-emerald-900">Design the ingestion pipeline and data model, justify storage choices, build three dashboard views, define a complete alert lifecycle, document security and retention, estimate cost drivers and score at least 80% in the quiz.</p></section>
 </article><ChapterQuiz/></>}

function ChapterQuiz(){const[a,setA]=useState({});const[s,setS]=useState(false);const score=useMemo(()=>questions.reduce((t,q,i)=>t+(a[i]===q.answer?1:0),0),[a]);const complete=Object.keys(a).length===questions.length;const passed=score>=8;return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 7 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=a[i]===j,correct=s&&j===q.answer,wrong=s&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":wrong?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"hover:bg-slate-50"}`}><input type="radio" name={`iot-ch7-${i}`} checked={selected} disabled={s} onChange={()=>setA(c=>({...c,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!s?<button disabled={!complete} onClick={()=>setS(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button onClick={()=>{setA({});setS(false)}} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}

function Flow({title,text}){return <div className="rounded-2xl bg-white p-5"><h4 className="font-bold text-blue-900">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
function Service({icon:Icon,title,text}){return <div className="rounded-2xl border p-5"><Icon className="text-indigo-700" size={27}/><h4 className="mt-3 font-bold">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
function Info({title,text}){return <div className="rounded-2xl border bg-white p-5"><h4 className="font-bold">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
function StoreRow({name,fit,example,watch}){return <tr><th className="p-4 font-bold text-white">{name}</th><td className="p-4">{fit}</td><td className="p-4">{example}</td><td className="p-4">{watch}</td></tr>}
function Retention({title,text}){return <div className="rounded-2xl border p-5"><h4 className="font-bold">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
function CodeBlock({code}){return <pre className="mt-5 overflow-x-auto rounded-2xl bg-slate-950 p-5 text-sm leading-7 text-cyan-100"><code>{code}</code></pre>}
function Dashboard({title,text}){return <div className="rounded-2xl bg-white p-5"><h4 className="font-bold text-violet-950">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
function AlertStep({number,title,text}){return <div className="rounded-2xl border p-5"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-red-600 font-bold text-white">{number}</span><h4 className="mt-3 font-bold">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
