import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, CircleHelp, Database, GitBranch, KeyRound, Lightbulb, LockKeyhole, MessageSquare, Network, RefreshCcw, RotateCcw, ShieldCheck, Tags, XCircle } from "lucide-react";

const questions=[
 {question:"What is the role of an MQTT broker?",options:["Receive publications and route them to matching subscribers","Measure analogue voltage","Power every sensor","Compile Arduino sketches"],answer:0},
 {question:"What does MQTT publish-subscribe decouple?",options:["Message producers from consumers","GPIO from ground","Power from voltage","Flash from firmware"],answer:0},
 {question:"What does QoS 0 provide?",options:["At most once delivery without protocol acknowledgement","Guaranteed exactly once delivery","Permanent message storage","Automatic encryption"],answer:0},
 {question:"What must an application expect with QoS 1?",options:["Possible duplicate delivery","No delivery attempts","No acknowledgement","Exactly one stored message forever"],answer:0},
 {question:"What is an MQTT retained message?",options:["The broker's latest retained value for a topic, delivered to new subscribers","A complete historical database","A private key","A Wi-Fi password"],answer:0},
 {question:"What is the purpose of Last Will and Testament?",options:["Let the broker publish a defined message after an unexpected client disconnect","Update ESP32 Flash","Increase radio power","Replace TLS"],answer:0},
 {question:"What does the + topic wildcard match?",options:["Exactly one topic level","Every possible level including none","Only retained messages","Only QoS 2 packets"],answer:0},
 {question:"Which client identifier practice is correct?",options:["Use a stable unique identifier per active client","Use the same ID for the entire fleet","Publish the password as the ID","Change it for every packet"],answer:0},
 {question:"Which control best protects an MQTT deployment?",options:["TLS, device authentication and topic-level least privilege","Anonymous full broker access","Secrets in topic names","Unbounded retained payloads"],answer:0},
 {question:"What should a command receiver do before acting?",options:["Authorise, validate, check freshness and make repeated delivery safe","Trust every payload","Ignore expiry","Execute received strings as code"],answer:0},
];

const topicTree=`nextgen/lab-1/
├── room-node-07/
│   ├── telemetry
│   ├── state
│   ├── status
│   └── command
└── gateway-01/status`;

const mqttCode=`#include <WiFiClientSecure.h>
#include <PubSubClient.h>
#include "secrets.h"

WiFiClientSecure secureClient;
PubSubClient mqtt(secureClient);

const char* telemetryTopic = "nextgen/lab-1/room-node-07/telemetry";
const char* commandTopic   = "nextgen/lab-1/room-node-07/command";
const char* statusTopic    = "nextgen/lab-1/room-node-07/status";

void onMessage(char* topic, byte* payload, unsigned int length) {
  if (length == 0 || length > 256) return;
  // Copy into a bounded buffer, parse JSON, validate schema,
  // authorise the command and check expiry before acting.
}

bool connectMqtt() {
  mqtt.setServer(MQTT_HOST, 8883);
  mqtt.setCallback(onMessage);
  secureClient.setCACert(ROOT_CA);

  bool connected = mqtt.connect(
    "room-node-07", MQTT_USER, MQTT_PASSWORD,
    statusTopic, 1, true, "offline"
  );
  if (connected) {
    mqtt.publish(statusTopic, "online", true);
    mqtt.subscribe(commandTopic, 1);
  }
  return connected;
}`;

export default function InternetOfThingsChapterSixLesson(){return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
 <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 6</p><h2 className="mt-2 text-3xl font-bold">MQTT Messaging and Publish-Subscribe Systems</h2><p className="mt-4 leading-8 text-slate-600">MQTT is a lightweight application messaging protocol designed around a broker and named topics. Devices publish messages without knowing which applications consume them, while subscribers receive only the topics they are authorised to use. This chapter explains how to design dependable telemetry, state and command flows instead of merely making a client connect.</p></header>

 <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Explain broker, publisher, subscriber, topic and message responsibilities.","Design maintainable topic hierarchies and apply + and # wildcards correctly.","Select QoS 0, 1 or 2 according to delivery and duplication requirements.","Use retained messages, persistent sessions and Last Will intentionally.","Build a secure ESP32 MQTT connection with unique identity and least privilege.","Handle reconnects, duplicates, stale commands and malformed payloads safely."].map(x=><li key={x} className="rounded-xl border p-4"><b className="mr-2 text-emerald-600">✓</b>{x}</li>)}</ul></section>

 <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><MessageSquare className="text-blue-700"/><h3 className="text-2xl font-bold text-blue-950">How publish-subscribe works</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Flow title="1. Connect" text="Each client authenticates to a broker using a unique client identity."/><Flow title="2. Subscribe" text="Consumers register topic filters and required delivery quality."/><Flow title="3. Publish" text="A producer sends a payload to a topic without addressing consumers."/><Flow title="4. Route" text="The broker applies permissions and forwards it to matching subscriptions."/></div><p className="mt-5 rounded-xl bg-white p-4 leading-7 text-slate-700">The broker is not automatically a historical database. It routes messages and may hold retained values or queued session messages. Long-term telemetry history normally belongs in a separate storage service.</p></section>

 <section><div className="flex items-center gap-3"><Tags className="text-indigo-700"/><h3 className="text-2xl font-bold">Topic hierarchy and naming</h3></div><pre className="mt-5 overflow-x-auto rounded-2xl bg-slate-950 p-5 text-sm leading-7 text-cyan-100"><code>{topicTree}</code></pre><div className="mt-5 grid gap-4 md:grid-cols-2"><Info title="Design for purpose" text="Separate telemetry, current state, status and commands so each flow can have different permissions, retention and processing."/><Info title="Keep secrets elsewhere" text="Topic names are routing metadata and may appear in logs. Never put passwords, tokens or private personal data in a topic."/><Info title="Use stable identifiers" text="Use documented site and device identifiers that remain meaningful through network-address changes."/><Info title="Plan versions" text="Version the payload schema or topic contract so deployed devices and services can evolve predictably."/></div></section>

 <section className="rounded-2xl border border-cyan-200 bg-cyan-50 p-6"><div className="flex items-center gap-3"><GitBranch className="text-cyan-700"/><h3 className="text-2xl font-bold text-cyan-950">Topic wildcards</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Wildcard symbol="+" title="Single-level wildcard" example="nextgen/+/room-node-07/status" text="Matches exactly one level in that position."/><Wildcard symbol="#" title="Multi-level wildcard" example="nextgen/lab-1/#" text="Matches all remaining levels and must appear at the end of the filter."/></div><p className="mt-5 rounded-xl bg-white p-4 leading-7 text-slate-700">Wildcards are used in subscription filters, not as normal publication topic names. Broad subscriptions can expose excess data and increase processing load; combine precise filters with broker access rules.</p></section>

 <section><h3 className="text-2xl font-bold">Quality of Service (QoS)</h3><div className="mt-5 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-4">QoS</th><th className="p-4">Delivery semantic</th><th className="p-4">Cost and behaviour</th><th className="p-4">Typical use</th></tr></thead><tbody className="divide-y"><QoS level="0" semantic="At most once" behaviour="Lowest overhead; no MQTT acknowledgement; loss is possible" use="Frequent telemetry where a later sample replaces a missed one"/><QoS level="1" semantic="At least once" behaviour="Acknowledged and retried; duplicates are possible" use="Important events designed for idempotent processing"/><QoS level="2" semantic="Exactly once at MQTT protocol level" behaviour="Highest handshake and state overhead" use="Rare cases where its additional cost is justified end to end"/></tbody></table></div><p className="mt-4 leading-7 text-slate-600">QoS is negotiated for each delivery path and does not guarantee that an application safely performs a physical action exactly once. Command handlers still need identifiers, expiry, deduplication and idempotent behaviour.</p></section>

 <section className="rounded-2xl bg-slate-900 p-6 text-white"><div className="flex items-center gap-3"><Database className="text-cyan-300"/><h3 className="text-2xl font-bold">Retained messages, sessions and Last Will</h3></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Dark title="Retained message" text="The broker stores the latest retained payload per topic and sends it immediately to a new matching subscriber. It is not a time-series history."/><Dark title="Session state" text="Depending on MQTT version and configuration, the broker can preserve subscriptions and queue eligible messages while a client is disconnected."/><Dark title="Last Will" text="The broker publishes a client-defined status if the network connection ends unexpectedly, helping consumers detect loss of presence."/></div><div className="mt-5 flex gap-3 rounded-xl border border-white/15 bg-white/10 p-4"><AlertTriangle className="mt-1 shrink-0 text-amber-300"/><p className="leading-7 text-slate-200">Do not retain transient commands unless the design explicitly prevents a newly connected device from executing an old instruction. Include creation time, expiry, command ID and desired-state semantics.</p></div></section>

 <section><div className="flex items-center gap-3"><Network className="text-blue-700"/><h3 className="text-2xl font-bold">MQTT message patterns</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Pattern title="Telemetry" topic=".../telemetry" text="Timestamped measurements; often QoS 0 or 1 according to loss tolerance."/><Pattern title="Reported state" topic=".../state/reported" text="The device's actual configuration and outputs."/><Pattern title="Desired state" topic=".../state/desired" text="Authorised target configuration; reconcile safely with reported state."/><Pattern title="Event" topic=".../event" text="A meaningful change such as a threshold crossing or detected fault."/><Pattern title="Command" topic=".../command" text="A bounded, validated request with identity, expiry and acknowledgement."/><Pattern title="Presence" topic=".../status" text="Online/offline or health information, often implemented with retained state and Last Will."/></div></section>

 <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><LockKeyhole className="text-red-700"/><h3 className="text-2xl font-bold text-red-950">Secure MQTT architecture</h3></div><div className="mt-5 grid gap-3 md:grid-cols-2">{["Use TLS and validate the broker certificate against a maintained trust anchor.","Give each production device a unique credential and client identifier.","Apply least-privilege publish and subscribe rules to exact topic branches.","Never expose broker credentials in public code, serial logs or topic names.","Limit payload size, rate, retained permissions and connection attempts.","Support credential rotation, device revocation and auditable administration."].map(x=><div key={x} className="flex gap-3 rounded-xl bg-white p-4"><CheckCircle2 className="mt-0.5 shrink-0 text-red-600" size={20}/><span>{x}</span></div>)}</div></section>

 <section className="rounded-2xl border border-violet-200 bg-violet-50 p-6"><div className="flex items-center gap-3"><KeyRound className="text-violet-700"/><h3 className="text-2xl font-bold text-violet-950">ESP32 secure-client structure</h3></div><p className="mt-3 leading-8 text-violet-900">The exact library API varies by version. The following structure demonstrates certificate validation, unique topics, bounded callbacks and a Last Will. Reconnect attempts must be scheduled with backoff rather than placed in a tight loop.</p><CodeBlock code={mqttCode}/><p className="mt-4 rounded-xl bg-white p-4 leading-7 text-slate-700"><code>mqtt.loop()</code> must run frequently after connection so the client processes incoming packets and keepalive traffic. Long blocking work can cause broker disconnection.</p></section>

 <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-center gap-3"><RefreshCcw className="text-amber-700"/><h3 className="text-2xl font-bold text-amber-950">Resilient connection lifecycle</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Resilience title="Reconnect with backoff" text="Classify Wi-Fi, DNS, TLS, authentication and broker rejection; increase delay with jitter and cap it."/><Resilience title="Restore subscriptions" text="After a new non-persistent session, subscribe again before declaring the service fully ready."/><Resilience title="Buffer intentionally" text="Use bounded queues with timestamps and an overflow policy; discard stale periodic samples when appropriate."/><Resilience title="Publish health" text="Report firmware version, uptime, signal, queue use and faults without exposing credentials."/></div></section>

 <section><h3 className="text-2xl font-bold">Command safety</h3><ol className="mt-5 space-y-3">{["Confirm the client is authorised to subscribe to the command topic.","Enforce a small maximum payload before copying or parsing.","Validate JSON schema, field types, ranges and allowed operations.","Verify command ID, target device, issue time and expiry.","Reject duplicates or make repeated execution produce the same safe result.","Apply local safety interlocks before controlling any actuator.","Publish an acknowledgement containing command ID, result and safe error code."].map((x,i)=><li key={x} className="flex gap-4 rounded-xl border p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-600 text-sm font-bold text-white">{i+1}</span><span>{x}</span></li>)}</ol></section>

 <section className="rounded-2xl bg-indigo-50 p-6"><div className="flex items-center gap-3"><Lightbulb className="text-indigo-700"/><h3 className="text-2xl font-bold text-indigo-950">Hands-on project: MQTT environmental node</h3></div><p className="mt-3 leading-8 text-indigo-900">Extend the environmental node so it publishes validated telemetry, reports online status and accepts a safe LED-mode command through an authenticated TLS broker.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{["Draw broker, device, dashboard and topic data flows.","Document exact publish and subscribe permissions for the node.","Publish versioned JSON telemetry with unit, timestamp and quality.","Configure retained online status and a broker-published offline Last Will.","Validate command size, schema, ID and expiry before changing the LED.","Test duplicate QoS 1 command, broker outage, reconnect and resubscription."].map(x=><div key={x} className="flex gap-3 rounded-xl bg-white p-4"><CheckCircle2 className="mt-0.5 shrink-0 text-indigo-600" size={20}/><span>{x}</span></div>)}</div></section>

 <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-emerald-700"/><h3 className="text-xl font-bold text-emerald-950">Verification checklist</h3></div><ul className="mt-4 space-y-2 leading-7 text-emerald-900"><li>• Unique client identity and credential confirmed.</li><li>• Broker certificate validation enabled.</li><li>• Publish/subscribe permissions follow least privilege.</li><li>• Retained and Last Will behaviour verified with a clean subscriber.</li><li>• Duplicate, malformed, stale and unauthorised commands remain safe.</li><li>• Reconnect uses backoff and restores required subscriptions.</li></ul></section>

 <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-950">Chapter revision summary</h3><ul className="mt-4 space-y-2 leading-7 text-blue-900"><li>• MQTT routes publications through a broker to matching topic subscriptions.</li><li>• Topic design, QoS, retained messages, sessions and Last Will solve different problems.</li><li>• QoS 1 can create duplicates; application processing must be safe to repeat.</li><li>• TLS, unique credentials and topic-level authorisation are production essentials.</li><li>• Robust clients validate commands, call the network loop frequently and reconnect with bounded backoff.</li></ul></section>
 <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h3 className="text-xl font-bold text-emerald-950">Chapter completion checklist</h3><p className="mt-3 leading-7 text-emerald-900">Design a topic tree, justify QoS choices, configure retained status and Last Will, implement secure connection and safe commands, test duplicate and outage scenarios, and score at least 80% in the quiz.</p></section>
 </article><ChapterQuiz/></>}

function ChapterQuiz(){const[a,setA]=useState({});const[s,setS]=useState(false);const score=useMemo(()=>questions.reduce((t,q,i)=>t+(a[i]===q.answer?1:0),0),[a]);const complete=Object.keys(a).length===questions.length;const passed=score>=8;return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 6 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=a[i]===j,correct=s&&j===q.answer,wrong=s&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":wrong?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"hover:bg-slate-50"}`}><input type="radio" name={`iot-ch6-${i}`} checked={selected} disabled={s} onChange={()=>setA(c=>({...c,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!s?<button disabled={!complete} onClick={()=>setS(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button onClick={()=>{setA({});setS(false)}} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}

function Flow({title,text}){return <div className="rounded-2xl bg-white p-5"><h4 className="font-bold text-blue-900">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
function Info({title,text}){return <div className="rounded-2xl border p-5"><h4 className="font-bold">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
function Wildcard({symbol,title,example,text}){return <div className="rounded-2xl bg-white p-5"><span className="rounded-lg bg-cyan-100 px-3 py-1 font-mono text-xl font-bold text-cyan-900">{symbol}</span><h4 className="mt-4 font-bold">{title}</h4><code className="mt-2 block text-sm text-cyan-800">{example}</code><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
function QoS({level,semantic,behaviour,use}){return <tr><th className="p-4 text-xl font-bold">{level}</th><td className="p-4 font-semibold">{semantic}</td><td className="p-4">{behaviour}</td><td className="p-4">{use}</td></tr>}
function Dark({title,text}){return <div className="rounded-2xl border border-white/15 bg-white/10 p-5"><h4 className="font-bold text-cyan-200">{title}</h4><p className="mt-2 leading-7 text-slate-200">{text}</p></div>}
function Pattern({title,topic,text}){return <div className="rounded-2xl border p-5"><h4 className="font-bold">{title}</h4><code className="mt-2 block text-sm text-blue-700">{topic}</code><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
function CodeBlock({code}){return <pre className="mt-5 overflow-x-auto rounded-2xl bg-slate-950 p-5 text-sm leading-7 text-cyan-100"><code>{code}</code></pre>}
function Resilience({title,text}){return <div className="rounded-2xl bg-white p-5"><h4 className="font-bold text-amber-950">{title}</h4><p className="mt-2 leading-7 text-slate-700">{text}</p></div>}
