import { useMemo, useState } from "react";
import { CheckCircle2, CircleHelp, FileCode2, FolderTree, HardDrive, Network, PackageCheck, RotateCcw, ShieldAlert, Terminal, XCircle } from "lucide-react";

const commandLab = `# Show identity, location and operating-system information
whoami
pwd
cat /etc/os-release

# List files, create a project folder and enter it
ls -la
mkdir -p ~/projects/chapter-3
cd ~/projects/chapter-3

# Create, inspect, copy, rename and remove a practice file
printf "Raspberry Pi Linux lab\\n" > notes.txt
cat notes.txt
cp notes.txt notes-backup.txt
mv notes-backup.txt linux-notes.txt
rm linux-notes.txt

# Inspect storage, memory, processes and networking
df -h
free -h
ps aux | head
ip address
hostname -I`;

const questions = [
  { question: "What does Raspberry Pi Imager do?", options: ["Writes a selected operating-system image to supported storage", "Changes GPIO voltage", "Replaces the power supply", "Measures temperature only"], answer: 0 },
  { question: "Why should important files on a target microSD card be backed up before imaging?", options: ["Imaging normally overwrites the card", "Linux cannot use files", "The card becomes read-only forever", "Wi-Fi requires it"], answer: 0 },
  { question: "Which command displays the current working directory?", options: ["ls", "pwd", "cd", "rm"], answer: 1 },
  { question: "What does sudo allow an authorised user to do?", options: ["Run an approved command with elevated privileges", "Increase GPIO voltage", "Format every drive automatically", "Disable passwords permanently"], answer: 0 },
  { question: "Which command updates the package index on Raspberry Pi OS?", options: ["sudo apt update", "pwd update", "mkdir apt", "cat install"], answer: 0 },
  { question: "What does the Linux root directory represent?", options: ["The top of the filesystem hierarchy", "Only the user's Downloads folder", "A GPIO pin", "The Wi-Fi password"], answer: 0 },
  { question: "Which command lists files, including hidden entries, in long format?", options: ["ls -la", "rm -rf", "pwd -h", "cd -a"], answer: 0 },
  { question: "Why should power not be removed while the operating system is writing data?", options: ["It can corrupt files or the filesystem", "It improves boot speed", "It changes HDMI type", "It safely upgrades the kernel"], answer: 0 },
  { question: "Which command reports filesystem space in human-readable units?", options: ["free -h", "df -h", "whoami", "mkdir -p"], answer: 1 },
  { question: "What is the safest way to stop a Raspberry Pi before unplugging it?", options: ["Use a proper operating-system shutdown", "Remove storage first", "Short the RUN pins", "Disconnect power during an update"], answer: 0 },
];

export default function RaspberryPiChapterThreeLesson() {
  return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
    <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 3</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Installing Raspberry Pi OS and Linux Essentials</h2><p className="mt-4 leading-8 text-slate-600">Raspberry Pi becomes a capable development computer when a suitable operating system is installed and configured correctly. This chapter takes you from preparing boot storage to using the Linux terminal, managing files and packages, inspecting system resources, and shutting down safely.</p></header>

    <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Select an appropriate Raspberry Pi OS edition and storage device.", "Use Raspberry Pi Imager and configure first-boot settings safely.", "Navigate the Linux filesystem from a terminal.", "Create, inspect, copy, move, and remove practice files.", "Update packages and inspect system, process, storage, and network status.", "Apply user-permission, backup, update, and shutdown good practices."].map(item=><li key={item} className="rounded-xl border border-slate-200 p-4"><b className="mr-2 text-emerald-600">✓</b>{item}</li>)}</ul></section>

    <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><HardDrive className="text-blue-700"/><h3 className="text-2xl font-bold">Choose the operating system and storage</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card icon={FileCode2} title="Raspberry Pi OS with desktop" text="Suitable for learners who want a graphical desktop, browser, editor, and terminal on a connected display."/><Card icon={Terminal} title="Raspberry Pi OS Lite" text="A smaller command-line system suited to headless servers, gateways, and remote projects."/><Card icon={HardDrive} title="Storage quality" text="Use reliable, adequately sized, supported storage. Back up existing data because imaging overwrites the target."/><Card icon={ShieldAlert} title="Architecture and model" text="Select an OS compatible with the Raspberry Pi model, required applications, and supported 32-bit or 64-bit architecture."/></div></section>

    <section><h3 className="text-2xl font-bold">Prepare Raspberry Pi OS</h3><ol className="mt-4 space-y-3">{["Download and install Raspberry Pi Imager on a trusted computer.", "Insert the target microSD card and confirm its identity and capacity carefully.", "Select the correct Raspberry Pi model and a suitable Raspberry Pi OS edition.", "Choose the target storage; remember that it will be erased.", "Use OS customisation to set hostname, user credentials, locale, time zone, keyboard, Wi-Fi, and SSH only as required.", "Write and verify the image, then eject the storage safely.", "Insert the card into the unpowered Pi, connect required peripherals, and apply the correct power supply."].map((item,i)=><li key={item} className="flex gap-4 rounded-xl bg-slate-50 p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-600 text-sm font-bold text-white">{i+1}</span><span>{item}</span></li>)}</ol></section>

    <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-amber-700"/><h3 className="text-xl font-bold">Before enabling remote access</h3></div><ul className="mt-4 space-y-2 text-slate-700"><li>• Use a unique username and a strong password or correctly managed SSH keys.</li><li>• Do not expose SSH directly to the public internet without a secure network design.</li><li>• Keep the system updated and disable services you do not need.</li><li>• Record the hostname and network ownership; do not join networks without permission.</li></ul></section>

    <section><div className="flex items-center gap-3"><FolderTree className="text-indigo-700"/><h3 className="text-2xl font-bold">Linux filesystem essentials</h3></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Path</th><th className="p-3">Typical purpose</th></tr></thead><tbody className="divide-y"><tr><td className="p-3 font-mono font-semibold">/</td><td className="p-3">Top of the filesystem hierarchy</td></tr><tr><td className="p-3 font-mono font-semibold">/home</td><td className="p-3">Home directories and personal project files</td></tr><tr><td className="p-3 font-mono font-semibold">/etc</td><td className="p-3">System-wide configuration</td></tr><tr><td className="p-3 font-mono font-semibold">/var</td><td className="p-3">Changing application data, caches, and logs</td></tr><tr><td className="p-3 font-mono font-semibold">/usr</td><td className="p-3">Installed programs, libraries, and shared resources</td></tr><tr><td className="p-3 font-mono font-semibold">/boot</td><td className="p-3">Boot-related files and configuration</td></tr></tbody></table></div><p className="mt-4 leading-7 text-slate-600">Linux paths are case-sensitive. Your home directory can be represented by <code>~</code>. Prefer working inside your home or project directories instead of changing protected system files.</p></section>

    <section><div className="flex items-center gap-3"><Terminal className="text-emerald-700"/><h3 className="text-2xl font-bold">Command-line practice lab</h3></div><p className="mt-3 leading-7 text-slate-600">Enter these commands one at a time. Read each result and verify the current directory before creating or deleting anything.</p><pre className="mt-5 overflow-x-auto rounded-2xl bg-slate-950 p-5 text-sm leading-6 text-emerald-300"><code>{commandLab}</code></pre></section>

    <section><div className="flex items-center gap-3"><PackageCheck className="text-purple-700"/><h3 className="text-2xl font-bold">Packages, permissions, processes and services</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card icon={PackageCheck} title="APT packages" text="Use sudo apt update to refresh package information, then sudo apt full-upgrade only after reviewing changes and ensuring stable power/network access."/><Card icon={ShieldAlert} title="Permissions and sudo" text="Linux separates users and privileges. Use elevated access only for a specific understood administrative command."/><Card icon={Terminal} title="Processes" text="ps, top, or htop show running programs. Stop a process gracefully before using stronger signals."/><Card icon={Network} title="Services" text="systemctl can inspect and manage background services. Enable only services the project actually needs."/></div><div className="mt-5 rounded-xl bg-slate-900 p-5 font-mono text-sm leading-7 text-cyan-200">sudo apt update<br/>sudo apt full-upgrade<br/>systemctl --failed<br/>journalctl -p warning -b</div></section>

    <section><h3 className="text-2xl font-bold">First-boot validation</h3><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Check</th><th className="p-3">Expected outcome</th></tr></thead><tbody className="divide-y"><tr><td className="p-3">Identity and locale</td><td className="p-3">Correct user, hostname, keyboard, time zone, and date</td></tr><tr><td className="p-3">Storage</td><td className="p-3">Root filesystem has adequate free space and no error warning</td></tr><tr><td className="p-3">Network</td><td className="p-3">Authorised network connection and expected IP address</td></tr><tr><td className="p-3">Updates</td><td className="p-3">Package metadata refreshed and reviewed updates installed</td></tr><tr><td className="p-3">Shutdown</td><td className="p-3">System shuts down cleanly before power is removed</td></tr></tbody></table></div></section>

    <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><h3 className="text-xl font-bold text-red-900">Common problems</h3><ul className="mt-4 space-y-2 text-slate-700"><li>• No boot: recheck model/OS compatibility, image verification, card insertion, display input, and power rating.</li><li>• Undervoltage or random reset: use a correctly rated supply and suitable cable; remove suspect peripherals.</li><li>• No network: verify country/locale, credentials, router permission, radio status, and IP configuration.</li><li>• Package failure: confirm time, DNS, network, free storage, and whether another package process is active.</li><li>• Never repeatedly remove power to recover; use logs and controlled troubleshooting.</li></ul></section>

    <section className="rounded-2xl bg-slate-900 p-6 text-white"><h3 className="text-2xl font-bold">Hands-on activity</h3><p className="mt-3 leading-7 text-slate-200">Prepare Raspberry Pi OS, complete the first boot, and create the Chapter 3 project directory using the command lab. Record the OS version, hostname, IP address, free storage, and memory. Create and remove only the practice files shown, run the update check, capture any failed services, then shut down correctly.</p></section>
    <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-900">Chapter completion checklist</h3><p className="mt-3 leading-7 text-blue-800">Complete OS imaging and first-boot validation, practise the Linux commands, review the uploaded video/PDF when available, demonstrate a proper shutdown, and score at least 80% below.</p></section>
  </article><ChapterQuiz/></>;
}

function ChapterQuiz(){const [answers,setAnswers]=useState({});const [submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;const reset=()=>{setAnswers({});setSubmitted(false)};return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b border-slate-200 pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 3 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border border-slate-200 p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=answers[i]===j;const correct=submitted&&j===q.answer;const incorrect=submitted&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":incorrect?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"border-slate-200 hover:bg-slate-50"}`}><input type="radio" name={`pi-ch3-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(a=>({...a,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!submitted?<button disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button onClick={reset} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}

function Card({icon:Icon,title,text}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><Icon className="text-blue-600" size={26}/><h4 className="mt-3 font-bold text-slate-900">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
