import { useMemo, useState } from "react";
import { CheckCircle2, CircleHelp, Code2, Cpu, Grid3X3, RotateCcw, ShieldAlert, Thermometer, XCircle, Zap } from "lucide-react";

const ledCode = `from gpiozero import LED
from time import sleep

# BCM GPIO 17, physical header pin 11
status_led = LED(17)

try:
    while True:
        status_led.on()
        sleep(1)
        status_led.off()
        sleep(1)
except KeyboardInterrupt:
    pass
finally:
    status_led.off()`;

const questions = [
  { question: "What voltage logic is used by Raspberry Pi GPIO?", options: ["3.3 V", "5 V tolerant on every pin", "12 V", "230 V AC"], answer: 0 },
  { question: "What does BCM numbering identify?", options: ["Only the physical header position", "The Broadcom GPIO channel number", "The microSD partition", "The HDMI port"], answer: 1 },
  { question: "Which physical header pin corresponds to BCM GPIO 17 on the common 40-pin header?", options: ["Pin 1", "Pin 6", "Pin 11", "Pin 40 only"], answer: 2 },
  { question: "Why is a series resistor used with a standard LED?", options: ["To limit current", "To increase supply voltage", "To add Wi-Fi", "To format storage"], answer: 0 },
  { question: "What is the safest action before changing GPIO wiring?", options: ["Run a CPU benchmark", "Shut down and remove power", "Short 3.3 V to ground", "Touch both power rails"], answer: 1 },
  { question: "What may happen if a 5 V output is connected directly to an unprotected GPIO input?", options: ["The GPIO may be permanently damaged", "The Pi gains memory", "The operating system updates", "Nothing under any condition"], answer: 0 },
  { question: "Why must motors and relays use suitable driver hardware?", options: ["GPIO cannot safely provide their required current and protection", "Python cannot control outputs", "They need an HDMI signal", "GPIO has no ground"], answer: 0 },
  { question: "What does gpiozero LED(17) normally mean?", options: ["Use physical pin 17", "Use BCM GPIO 17", "Use 17 volts", "Blink 17 times automatically"], answer: 1 },
  { question: "Why can cooling be important on higher-performance Raspberry Pi models?", options: ["Sustained load produces heat and may reduce performance", "It changes GPIO to 5 V", "It replaces storage", "It enables Ethernet"], answer: 0 },
  { question: "Which connection is required as the reference between Raspberry Pi and a compatible external circuit?", options: ["A correctly shared ground where required", "A direct mains wire", "Only HDMI", "No reference connection"], answer: 0 },
];

export default function RaspberryPiChapterTwoLesson() {
  return <><article className="space-y-8 rounded-3xl bg-white p-6 shadow-lg md:p-8">
    <header><p className="font-semibold uppercase tracking-wider text-blue-700">Chapter 2</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Raspberry Pi Hardware, GPIO and Safe Setup</h2><p className="mt-4 leading-8 text-slate-600">The Raspberry Pi exposes powerful computer interfaces and a general-purpose input/output header on the same board. This chapter develops the hardware awareness needed to select the correct pins, protect 3.3 V GPIO, power peripherals safely, and prepare a dependable development setup.</p></header>

    <section><h3 className="text-2xl font-bold">Learning objectives</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{["Identify the Raspberry Pi's major hardware blocks and connectors.", "Distinguish physical pin numbering from BCM GPIO numbering.", "Recognise power, ground, GPIO, I2C, SPI, UART, and PWM functions.", "Apply voltage, current, grounding, and driver-interface rules.", "Plan power, case, airflow, and cooling for a stable system.", "Build and test a current-limited LED output safely."].map(item=><li key={item} className="rounded-xl border border-slate-200 p-4"><b className="mr-2 text-emerald-600">✓</b>{item}</li>)}</ul></section>

    <section className="rounded-2xl bg-blue-50 p-6"><div className="flex items-center gap-3"><Cpu className="text-blue-700"/><h3 className="text-2xl font-bold">Hardware architecture</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Card icon={Cpu} title="Processor and memory" text="The system-on-chip runs the operating system and applications; RAM holds active programs and data."/><Card icon={Grid3X3} title="Peripheral controllers" text="USB, display, camera, storage, networking, and GPIO controllers connect the processor to external devices."/><Card icon={Zap} title="Power subsystem" text="Regulators create the board's internal supply rails from a correctly rated external input."/><Card icon={Thermometer} title="Thermal system" text="Heat spreaders, sinks, airflow, and active cooling maintain reliable performance under sustained load."/></div></section>

    <section><h3 className="text-2xl font-bold">Understanding the 40-pin header</h3><p className="mt-4 leading-8 text-slate-600">The header combines power, ground, and programmable signal pins. Physical numbering describes positions 1–40 on the connector. BCM numbering identifies the processor's GPIO channels and is commonly used by Python libraries. Always state which scheme a diagram or program uses.</p><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Category</th><th className="p-3">Purpose</th><th className="p-3">Key rule</th></tr></thead><tbody className="divide-y"><tr><td className="p-3 font-semibold">3.3 V / 5 V power</td><td className="p-3">Supply compatible low-power circuits</td><td className="p-3">These are power rails, not normal GPIO</td></tr><tr><td className="p-3 font-semibold">Ground</td><td className="p-3">Electrical reference and return path</td><td className="p-3">Use a correct common reference where required</td></tr><tr><td className="p-3 font-semibold">Digital GPIO</td><td className="p-3">Read or drive 3.3 V logic states</td><td className="p-3">Never apply an excessive or negative voltage</td></tr><tr><td className="p-3 font-semibold">I2C / SPI / UART</td><td className="p-3">Communicate with compatible peripherals</td><td className="p-3">Check voltage, pin mapping, and bus configuration</td></tr><tr><td className="p-3 font-semibold">PWM-capable GPIO</td><td className="p-3">Generate timed output waveforms</td><td className="p-3">Use a driver for power loads</td></tr></tbody></table></div></section>

    <section className="rounded-2xl border border-red-200 bg-red-50 p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-red-700"/><h3 className="text-xl font-bold">GPIO electrical limits</h3></div><ul className="mt-4 space-y-2 text-slate-700"><li>• Raspberry Pi GPIO uses 3.3 V logic and is not generally 5 V tolerant.</li><li>• A GPIO pin is a logic signal, not a power source for motors, relays, heaters, or high-current LEDs.</li><li>• Use a transistor, MOSFET, relay module, or motor driver with suitable protection for power loads.</li><li>• Use level shifting or a correctly designed divider/interface when voltage domains differ.</li><li>• Avoid driving the same line from two outputs and never short a power rail to ground.</li><li>• Verify the official documentation for the exact Raspberry Pi model and peripheral.</li></ul></section>

    <section><h3 className="text-2xl font-bold">Stable power and thermal setup</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><Card icon={Zap} title="Power budget" text="Select a regulated supply for the exact model and include USB devices, storage, display, and attached boards in the current budget."/><Card icon={ShieldAlert} title="Cable quality" text="A poor or overly long cable can cause voltage drop, undervoltage warnings, resets, and storage corruption."/><Card icon={Thermometer} title="Cooling" text="Fit the recommended passive or active cooling for the model, enclosure, ambient temperature, and workload."/><Card icon={Grid3X3} title="Mechanical protection" text="Use standoffs and a ventilated case; prevent conductive objects from contacting the underside or GPIO header."/></div></section>

    <section><div className="flex items-center gap-3"><Code2 className="text-emerald-700"/><h3 className="text-2xl font-bold">First GPIO output: current-limited LED</h3></div><p className="mt-4 leading-8 text-slate-600">With the Pi shut down and unplugged, connect BCM GPIO 17 (physical pin 11) through a suitable series resistor to the LED anode, and connect the LED cathode to ground. Recheck LED polarity and pin numbering before powering the Pi. This example uses the <code>gpiozero</code> library.</p><pre className="mt-5 overflow-x-auto rounded-2xl bg-slate-950 p-5 text-sm leading-6 text-emerald-300"><code>{ledCode}</code></pre><p className="mt-4 text-slate-600">Run the script from a terminal and stop it with Ctrl+C. The <code>finally</code> block leaves the LED off when the program exits normally through the keyboard interrupt.</p></section>

    <section><h3 className="text-2xl font-bold">Safe setup sequence</h3><ol className="mt-4 space-y-3">{["Shut down the operating system, disconnect power, and remove external supplies.", "Choose one numbering scheme and mark every required pin on a trusted pinout.", "Build the circuit with a current-limiting resistor and check LED polarity.", "Verify that no power rail is shorted and no 5 V signal reaches a GPIO.", "Apply power, start the Pi, and run the smallest possible test program.", "Stop the program, confirm the output returns to a safe state, and document the result."].map((item,i)=><li key={item} className="flex gap-4 rounded-xl bg-slate-50 p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-600 text-sm font-bold text-white">{i+1}</span><span>{item}</span></li>)}</ol></section>

    <section className="rounded-2xl bg-slate-900 p-6 text-white"><h3 className="text-2xl font-bold">Hands-on activity</h3><p className="mt-3 leading-7 text-slate-200">Create a pin table containing physical pin, BCM number, function, direction, and connected device for the LED circuit. Photograph or sketch the unpowered wiring, have the mapping checked, then run the blink program. Change the on/off intervals and record what changes. Finally, stop the program and perform a proper system shutdown.</p></section>
    <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h3 className="text-xl font-bold text-blue-900">Chapter completion checklist</h3><p className="mt-3 leading-7 text-blue-800">Identify the hardware blocks, explain BCM versus physical numbering, complete the safe LED activity, review the uploaded video/PDF when available, and score at least 80% below.</p></section>
  </article><ChapterQuiz/></>;
}

function ChapterQuiz(){const [answers,setAnswers]=useState({});const [submitted,setSubmitted]=useState(false);const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);const complete=Object.keys(answers).length===questions.length;const passed=score>=8;const reset=()=>{setAnswers({});setSubmitted(false)};return <section className="rounded-3xl bg-white p-6 shadow-lg md:p-8"><div className="flex items-center gap-3 border-b border-slate-200 pb-5"><CircleHelp className="text-blue-600" size={30}/><div><h2 className="text-2xl font-bold">Chapter 2 Quiz</h2><p className="text-sm text-slate-500">10 questions • Pass mark: 80%</p></div></div><div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={q.question} className="rounded-2xl border border-slate-200 p-5"><legend className="px-2 font-bold">{i+1}. {q.question}</legend><div className="mt-3 space-y-2">{q.options.map((o,j)=>{const selected=answers[i]===j;const correct=submitted&&j===q.answer;const incorrect=submitted&&selected&&j!==q.answer;return <label key={o} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${correct?"border-green-300 bg-green-50":incorrect?"border-red-300 bg-red-50":selected?"border-blue-400 bg-blue-50":"border-slate-200 hover:bg-slate-50"}`}><input type="radio" name={`pi-ch2-${i}`} checked={selected} disabled={submitted} onChange={()=>setAnswers(a=>({...a,[i]:j}))} className="mt-1"/><span>{o}</span></label>})}</div></fieldset>)}</div>{!submitted?<button disabled={!complete} onClick={()=>setSubmitted(true)} className="mt-6 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white disabled:bg-slate-300">Submit Quiz</button>:<div className={`mt-6 rounded-2xl border p-6 ${passed?"border-green-300 bg-green-50":"border-red-300 bg-red-50"}`}><div className="flex gap-3">{passed?<CheckCircle2 className="text-green-700"/>:<XCircle className="text-red-700"/>}<div><h3 className="text-xl font-bold">{passed?"Chapter quiz passed":"Review the lesson and try again"}</h3><p>You scored {score}/10 ({score*10}%).</p></div></div><button onClick={reset} className="mt-5 inline-flex items-center gap-2 rounded-xl border bg-white px-5 py-2.5 font-semibold"><RotateCcw size={18}/> Retake Quiz</button></div>}</section>}

function Card({icon:Icon,title,text}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><Icon className="text-blue-600" size={26}/><h4 className="mt-3 font-bold text-slate-900">{title}</h4><p className="mt-2 leading-7 text-slate-600">{text}</p></div>}
